// var oh_cmll = {
// 	"T": ["R U2 R' U' R U' R2 U2 R U R' U R", "r' U r U2 R2 F R F' R!R' U R U2 R' L' U R U' r x'", "(U') F R U' R' U R U R' F'", "(U2) F R U R' U' R U' R' U' R U R' F'", "(U') R U R' U' R' F R F'", "R' U' R U' R' U R U' R' U F' U F R!(U2) R' F' U' F U' R U R' U' R U R' U R"],
// 	"U": ["(U') R' U' R U R' U R U2' R' U R U2' R' U' R!R' U' R U' R' U2' R2 U R' U R U2' R'", "(U2) F R U R' U' R' U R U' F' U R' U' R", "R' U2' R U2 F U' R' U R U F'", "F R U' R' U R U R' U R U' R' F'", "R2 D' R U2 R' D R U2 R", "(U') F R U R' U' F'!(U) F U R U' R' F'"],
// 	"L": ["(U) R' U' R U' R' U R U' R' U R U' R' U2' R!(U2) R U R' U R U' R' U R U' R' U R U2 R'", "R' U' R U' R' U2' R2 U R' U' R' F R F'!F U' R' U' R U F' U2' R' U2 R", "F R' F' R U R U' R'", "F R U' R' U' R U R' F'", "(U') R' U2 R' D' R U2 R' D R2", "R U2 R2 F R F' R U2 R'!(U2) R' U' R U' F U' R' U' R U F'!R U2 r2 F R F' R U2' R'"],
// 	"S": ["(U) R U R' U R U2' R'!R' U2' R U R' U R", "(U) F R' F' R U2' R U2 R'", "(U2) R' U' R U' R' U2 F R F' r U r'!(U) R U R' U' R' F R F' R U R' U R U2' R'", "(U) r U' r' F R' F' R!(U) R U' r' F R' F' r!(U) R U' L' U R' U' L", "(U') R' U2 R U2 R f' U' f!(U) F U R U2 R' U' R U R' F'", "(U2) R U R' U R' F R F' R U2 R'"],
// 	"AS": ["(U2) R U2 R' U' R U' R'!(U) R' U' R U' R' U2 R", "(U2) F R U' R' U R U2 R' U' F'", "(U') R U2 R' U2 R' F R F'", "(U') R' F R F' r U r'!(U') r' F R F' r U R'", "r U' r' F R' F' U2 R U R' U R", "R' U' R U' R' U R' F R F' U R"],
// 	"Pi": ["F R U R' U' R U R' U' F'!(U2) F U R U' R' U R U' R' F'", "(U) F U R U' R2' F' R U2 R U2' R'!(U) F R' F' R U2 R U' R' U R U2 R'", "(U') F R U' R' U' R U R' U R U' R' F'", "R U2 R' U' R U R' U2' R' F R F'!R U2' R' U2 R' F R2 U R' U' F'", "(U2) R' F R F' r U' R' U' R U' r'!(U2) R' F R F' r U' r' U' R U' R'!(U2) r' F R F' r U' R' U' R U' R'", "(U') R' U' R' F R F' R U' R' U2' R!(U2) R' U' R U' R' U F' U F R"],
// 	"H": ["(U) R' U' R U' R' U R U' R' U2 R!R' U2' R U' R' U' R U R' U R!(U) R U R' U R U' R' U R U2' R'", "(U') R U R' U R U r' F R' F' r!(U') R' U' R U' R' U' z U R' D R U' z'", "(U) F R U' R' U R U2 R' U' R U R' U' F'!(U') F R U R' U' R U' R' U R U R' F'", "F R U R' U' R U R' U' R U R' U' F'"],
// 	"O": ["R U2 R' U' R U2 L' U R' U' L!R U2 R' U' R U2 r' F R' F' r!R U R' F' R U R' U' R' F R2 U' R'!R U R' U' R' F R2 U' R' U' R U R' F'!R' U2' R U R' U' U' z U R' D R U' z'", "F R U' R' U' R U R' F' R U R' U' R' F R F'!x U' R' U R U' x' R U R' F U2' R U2 R'"],
// };

// var CMLL = {
//     'O': ["R U R' F' R U R' U' R' F R2 U' R'!r U R' F' R U R' U' R' F R2 U' r'!r' F R F' r U2 R' U R U2 R'!r U R' U' r' F R2 U' R' U' R U R' F'", "F R U' R' U' R U R' F' R U R' U' R' F R F'!r' U' r' D' r U' r' D r U r' D' r U r' D r2!r2 D r' U r D' R2 U' F' U' F!F (R U r U2') (R2' F R F') (R U2' R') r' F'!F R' F R2 U' R' U' R U R' F' R U R' U' F'"],
//     'H': ["R U2 R' U' (R U R' U') R U' R'!(U) R U R' U R U' R' U R U2 R'!r U2 R' U' R U R' U' R U' r'!(U) r U R' U R U' R' U R U2 r'", "(r U' r' F) U2' r2' F r U' r!(U2) r U' r2 D' r U' r' D r2 U r'!(U') R' F' R U2 R U2 R' F U' R U' R'!(U') R U R' U R U r' F R' F' r", "(U) F R U R' U' F' R U R' U' R' F R F'!(U) R U2' R2' F R F' U2 R' F R F'!(U) F R U' R' U R U2 R' U' R U R' U' F'!(U) F R U R' U' F' r U R' U' r' F R F'!(U) f R U R' U' f' R U R' U' R' F R F'!(U2) R' F' R U2 R' F2 R U' F U F'", "F R U R' U' R U R' U' R U R' U' F'!R' F R U2 R' F' R U F R U R' U F'"],
//     'Pi': ["F (R U R' U' R U R' U') F'!R U2' R2' U' R2 U' R2' U2' R!f R U R' U' R U R' U' f'!r U' r2 U r2 U r2 U' r!r' U r2 U' r2 U' r2 U r'!(U2) F (U R U' R') (U R U' R') F' ", "(U) (F R' F' R) U2 (R U' R' U) (R U2' R')!(U) F (U R U' R') (U R U' R2) F' (R U R U') R'!R' F2 R U2 R U2 R' F2 U' R U' R'!(U) R U2 R' U' R U' R2 U L U' R U L'", "(U') R' F R U F U' R U R' U' F'!R' F2 D R2 U' R2 D' F2 R!R' F2 y' U R2 U' R2' U' y F2 R!(U') F R U' R' U' R U2 R' U' R U R' U' F'", "R U2 R' U' R U R' U2' R' F R F'!R U R' U' R' F R2 U R' U' R U R' U' F'!(U') R' U2 R U R' U R2 U' L' U R' U' L", "(U2) R' U R U' R2' F R2 U R' U' F' R!(U') r U' r2 D' r U r' D r2 U r'!(U2) R' F R F' r U' R' U' R U' r'!(U2) r' F R F' r U' R' U' R U' R'!(U2) R' U R U' R2' F R2 U R' U' F' R", "(U') (R' U' R') (F R F') (R U' R') U2 R!(U) R U2 R' U' F' R U2 R' U' R U' R' F R U' R'!(U2) R' U' R U' R' U F' U F R!(U') (R U R' U) (r' F R F') (r U' R' U) (R U2 R')"],
//     'U': ["R' U' R U' R' U2 R2 U R' U R U2 R'!R2' (F U' F U) (F2 R2) U' (R' F R)!(U2) r U R' U R U2 r2 U' R U' R' U2 r", "(U') (F R2) (D R' U R D') R2' U' F'!(U') R2 F R F' R U2 R' F' U2 F R!(U') f R2 D R' U R D' R2 U' f!(U) R' F R U' R' U' R U R' F' R U R' U' R' F R F' R", "(U2) R2 D R' U2 R D' R' U2 R'!r U' r' U' r U' r' U' F' U2 F!R' U2 R U R2 F' R U R U' R' F R!(U2) r U' r' U2 r' D' r U2 r' D r", "(U2) (r U' r' U) r' D' (r U' r') D r!F (R U' R' U) (R U R' U) (R U' R' F')!R U R' U' R' F2 R2 U' R' U' R U R' F2!(U2) R' F U' R F R' U R F'!(U') R' D R U' R U' R' U R' D' R", "R2' D' R U2 R' D R U2 R!R' F R U R' F R U F U2' F'!R2 D' r U2 r' D R U2 R!r' U r U2 r D r' U2 r D' r'", "(U') F R U R' U' F'!R2' D' (R U R') D (R U R U') (R' U' R)!(U') f R U R' U' f'!(U2) R' U' F' U F R!(U) R' U' R' F R F' U R!(U') R U2 R2 F R F' U2 M' U R U' r'"],
//     'T': ["R U2 R' U' R U' R2 U2 R U R' U R!(F R' F) R2 U' (R' U' R U) R' F2!(U)' R U R' U R U' R' U R' U' R2 U' R2' U2' R!(r U2 R' U' R U') r2 (U R' U R U2 r')", "(r' U r) U2' R2' (F R F' R)!(R' U r) U2' R2' (F R F' r)!R' U R U2 r' R' F R F' r", "(U) L' U' L U L F' L' F!(U') F R U' R' U R U R' F'!(U) r' F' r U r U' r' F!(U2) R' U' R' D' R U R' D R2", "(r' D') (r U r') D r (U' r U r')!(U2) F (R U R' U') (R U' R' U') (R U R' F')!(U) R' D R U' R U R' U R' D' R", "(U') R U R' U' R' F R F'!(U') r U R' U' r' F R F'!(U') S R U R' U' R' F R f'", "(U2) (r2 D') (r U r') (D r2) (U' r' U' r)!(U2) r U' r2 D' r U2 r' D r2 U r'!(U) R U2 R2 F R F' R U' R' U R U2 R'!R' U R2 D r' U2 r D' R2' U' R"],
//     'S': ["R U R' U R U2 R'!r U R' U R U2 r'!(U') R' U2 R U R' U R", "r' F2 r U2 r U' r' F!R' F2 r U2 r U' r' F (M')!(U2) R' U2 R U2 R f' U' f", "F R' F' R U2 R U2 R'!M' F R' F' R U2 R U2 r'", "R U R' U' R' F R F' R U R' U R U2 R'!(U) R' U' R U' R2' F' R U R U' R' F U2' R", "R U' L' U R' U' L!r U' r' F R' F' R", "(U2) (R U R' U) R' F R F' (R U2 R')!(U2) r U R' U R' F R F' R U2 r'!R' U2 R U R' U R U' f R U R' U' f'"],
//     'aS': ["(U') R U2 R' U' R U' R'!(U2) R' U' R U' R' U2 R", "R U2 R' U2 R' F R F'!r U2 R' U2 R' F R F' (M')", "L' U R U' L U R'!R' F R F' r U r'!r' F R F' r U R'", "R2 D R' U R D' R' U R' U' R U' R'!(U') r R D R' U R D' R' U R' U' R U' r'", "F' L F L' U2 L' U2 L!F' r U r' U2 r' F2 r!M' F' r U r' U2 r' F2 R", "(U2) R U R' F' (R U2 R' U' R U' R') F R U' R'!(U2) L' U' L U' L F' L' F L' U2 L!(U2) R U2 R' F R' F' R U' R U' R'!(U) R' U' R U' R' U R' F R F' U R!R' U' R U' L U' R' U L' U2 R!(U) R' U' R U' R' U R' F R F' U R"],
//     'L': ["(U2) R U R' U R U' R' U R U' R' U R U2 R'!(U2) R U2 R' U' R U R' U' R U R' U' R U' R'", "R U2 R D R' U2 R D' R2!R U R' U' F' U2' F U R U R'!(U2) R U R' U R' F R F' U2 R' F R F'", "F R' F' R U R U' R'!F R' F' r U R U' r'", "F R U' R' U' R U R' F'!(U) F' r U R' U' r' F R", "(U') R' U2 R' D' R U2 R' D R2", "(R U2 R2) (F R F') (R U2 R')!(U2) R' U' R U R' F' R U R' U' R' F R2!r U2 R2 F R F' R U2 r'"]
// };

var uf_edges = {
    "UB": ["R2 U': S, R2", "L2 U: S', L2", "R' U': S, R2", "R' F': R U R', E", "L U: S', L2", "U M: U/M'", "U/L' E L", "U'/R' E' R", "U/L E' L'", "L' U: S', L2", "U M': U/M'", "R U': S, R2", "U' M: U'/M'", "U'/R' E R", "U/L E L'", "U'/R E' R'", "U2, M'", "U': S, R2", "M, U2", "U: S', L2"],
    "UR": ["R2 U': R2, S", "M2: U/M", "E': U', R' E R", "M', R U' R' U", "U', R E2 R'", "U: L' E L, U", "U', R' E' R", "U: L E' L', U", "M, R' U' R U", "U', R' E2 R", "U M U M' U M U M'", "E: U', R E' R'", "S', L F' L'", "U', R' E R", "U: L E L', U", "U', R E' R'", "M U2 M, U", "U', R E' R2 E R", "R U R': U'/M", "l F: L'/S'"],
    "UL": ["L2 U: L2, S'", "M2: U'/M", "U, L' E2 L", "M', L' U L U'", "E: U, L E' L'", "S, R' F R", "U, L' E L", "U': R' E' R, U'", "U, L E' L'", "M, L U L' U'", "E': U, L' E L", "U' M U' M' U' M U' M'", "U, L E2 L'", "U': R' E R, U'", "U, L E L'", "U': R E' R', U'", "M U2 M, U'", "U R U R' U' R' U' R' U R", "U l: U'/R' E R", "U, L' E L2 E' L'"],
    "LU": ["U' M: U/M'", "L F' L', S'", "S' U: L'/E'", "U' D: S', R' F R", "r U: r' E r, U", "M: U/M'", "r': U/M'", "R' F: R/S", "R M: U/M'", "L' U' L U, M'", "U' l: U/M'", "D' R' F: R/S", "M': U', L' E L", "S: U', R' E R", "l' U: L'/S'", "S: U', R E' R'", "L' F': L2, E'", "r: U', L E' L'", "D: L F' L', S", "L F' L', S"],
    "LF": ["U/R' E R", "R' E R, U'", "U2: R' E R, U", "E, R U' R'", "M2: U' L' U, M", "U' r': R U' R', E", "r U: R'/E", "M' U: R'/E", "U E: R'/S", "U' L' U, M'", "E', L U L'", "U' M: U, R' E R", "R': R' E R, U'", "S: R' E R, U'", "L, U S' U'", "M' U: L/S'", "U R' F2: R S R', F", "U' E': R/E'", "M/U' L' U", "U E: L/E'"],
    "LD": ["U'/L E L'", "U2: L E L', U'", "L E L', U", "U: L F2 L', S", "U: L F L', S", "S' U': R/E", "L F': L/S'", "L F': E, L2", "R' F: R'/S'", "M' U': L'/E'", "U' D: S, R' F' R", "S' U': R'/E'", "U: L' B' L, S", "L E: L' U L, E", "l' U: L/S'", "U S' U', L", "U S' U', L'", "L F: E', L2", "L' F' L, S", "U: S', L B' L'"],
    "LB": ["U/R E' R'", "R E' R', U'", "U2: R E' R', U", "R: R E' R', U'", "U' M': U', R E' R'", "E, L' U L", "l: U/M'", "u: R/S", "R' F: R2, E'", "R2 F: R2, E'", "U' L U, M'", "U' M: U, R E' R'", "E', R' U' R", "S: R E' R', U'", "M' U: L'/S'", "L', U S' U'", "F: E', L2", "u': R'/E", "M/U' L U", "u: L'/E"],
    "FR": ["R' U': R2, S", "E': R' E R, U'", "L' E2 L, U", "M', U' R U", "R' U': R/E", "R' U' E': R/E", "R U' R', E'", "R' u': R'/E'", "M, U' R U", "R' U': R'/E'", "U2: M, U R U'", "U: R'/S", "S' U: L/E'", "R U' R', E", "U: S, L F2 L'", "R: U', R E' R'", "U D': L/E'", "U R' U' R' U R U R U R' U2", "U D: L/E'", "U: L/E'"],
    "FD": ["R' F': E, R U R'", "R U' R' U, M'", "L' U L U', M'", "U' R U, M'", "U L' U', M'", "R' F': E, R U' R'", "M': U R' U', M'", "U': S', R' F' R", "M': U R U', M'", "U': S, R' F' R", "U L U', M'", "U M' U' M U2 M U M' U", "U' R' U, M'", "U' D: R' F R, S'", "M': U' L' U, M'", "U: S, L F L'", "U' M': R E' R', U'", "U R' F': R'/S", "D': L' F' L, S", "U' L F: L/S'"],
    "FL": ["L U: L2, S'", "R E2 R', U'", "E: L E' L', U", "R' U': R'/E", "M', U L' U'", "S U': R'/E", "L': U, L' E L", "U': S', R' F2 R", "L' U L, E'", "M, U L' U'", "U': L/S'", "U2: M, U' L' U", "R U': R'/E", "r U: U, r' E r", "S' U': R'/E", "L' U L, E", "U' D: R'/E", "U':  R'/E", "U' D': R'/E", "U' L U L U' L' U' L' U' L U2"],
    "RU": ["U M: U'/M'", "R' F R, S", "R' U' E': R'/E", "R' F': R U' R', E", "S U': R/E", "S': U, L' E L", "R E' R' U': R/E", "S': U, L E' L'", "R U R' U', M'", "S U': R'/E'", "U D: S, L F' L'", "R u': R/E'", "M: U'/M'", "U' M: R' E R, U'", "L F': L'/S'", "l: U'/M'", "D: R' F R, S'", "R' F R, S'", "D': R' F R, S'", "l': U, R' E R"],
    "RB": ["U'/L' E L", "U2: L' E L, U'", "L' E L, U", "E', R U' R'", "M2: U R' U', M", "L': L' E L, U", "S': L' E L, U", "R, U' S U", "M' U': R/S", "U R' U', M'", "E, L U L'", "U M: U', l' E l", "r': U'/M'", "r U: R/E", "L F': L2, E", "u: R'/S", "F': E, R2", "u': R/E'", "M/U R' U'", "u: L/E'"],
    "RD": ["U/R' E' R", "R' E' R, U'", "U2: R' E' R, U", "R' u': R/E'", "U': R' F' R, S'", "U': R' F2 R, S'", "R E' R' U': R'/E", "U' S U, R", "U' S U, R'", "U' D': S, R' F' R", "R' E': R U' R', E'", "U': l U l', S'", "D': U' R' U, M'", "R' F: R'/S", "M' U: R/E", "L F': L/S", "R' F: E', R2", "R' F': E, R2", "U': S, R' B R", "R F R', S'"],
    "RF": ["U'/L E' L'", "U2: L E' L', U'", "L E' L', U", "M': M', U R U'", "E', L' U L", "S': L E' L', U", "M' U': R'/S", "R', U' S U", "U R U', M'", "L: L E' L', U", "U M: U', L E' L'", "E, R' U' R", "R M: U'/M'", "U E: R/S", "M' U': L/E'", "R2 F: E', R2", "R2 F': E, R2", "U' E': R'/E", "M/U R U'", "U E: L'/E"],
    "BU": ["R' U' R U, M", "L U L' U', M", "U' R U, M", "U': R' F' R, S", "U L' U', M", "M', R U R' U'", "M', U R' U'", "U' D': R' F' R, S", "M', U R U'", "U L U', M", "U': R B R', S", "U' R' U, M", "M', L' U' L U", "M', U' L' U", "U' D: R' F' R, S", "M', U' L U", "U: S, R' F' R", "U D': S, R' F' R", "U: S, l U l'", "U D: S, R' F' R"],
    "BL": ["L' U: L2, S'", "R' E2 R, U'", "E': L' E L, U", "R' U': R/E'", "M', U L U'", "U': L'/S'", "S U': R/E'", "L U L', E", "R' E2: R U' R', E", "L: U, L E' L'", "M, U L U'", "U2: M, U' L U", "R U': R/E'", "U' l: U'/M'", "L U L', E'", "S' U': R/E'", "U' D: R/E'", "U': R/E'", "U' D': R/E'", "U' L' U' L' U L U L U L'"],
    "BD": ["U M': U'/M'", "M U' M' U' M U' M' U'", "M U M' U M U M' U", "U': R, U' M U", "U M U M' U2 M' U' M U", "U: L', U M U'", "U D: S, L F' L'", "U M: l' E l, U'", "U': S', l U l'", "U l: E', L' U' L", "U': S, l U l'", "U: L, U M U'", "U': R', U' M U", "U' D': S', R' F R", "U' r': E, R U R'", "U: S, r' U' r", "U' M: R E' R', U", "D: L' F' L, S", "D' R' F': E, R2", "D L F: E', L2"],
    "BR": ["R U': R2, S", "E: R E' R', U'", "L E2 L', U", "U: R/S", "M', U' R' U", "R U': R/E", "R u': R'/E'", "D': M', U' R' U", "R' U' R, E", "M, U' R' U", "R U': R'/E'", "U2: M, U R' U'", "S' U: L'/E", "R': U', R' E R", "L E2: L' U L, E'", "R' U' R, E'", "U R': U/M'", "U R U R U' R' U' R' U' R", "M2, U' R' U", "U: L'/E"],
    "DF": ["M', U2", "L: F'/L' S' L", "R': F/R S R'", "U D': L'/E'", "U' D: R/E", "D: S', R' F R", "F': R2, E", "R' F':  R2, E", "R2 F': R2, E", "U: R' F' R, S", "U' D: R'/E'", "D: S, L' F' L", "U R': U'/M'", "L' F': E', L2", "U R' F': R S R', F'", "L F: L2, E'", "F: L2, E'", "R': F/R S' R'", "u2 M' u2 M'", "L: F'/L' S L"],
    "DR": ["U': R2, S", "R' U: R/S", "R' U' R U R U R U' R' U'", "U2 R U' R' U' R' U' R U R U'", "U R' F': R/S", "U': R/E", "S', R' F R", "u': R'/E'", "U' E': R/E", "U D': R' F' R, S", "U': R'/E'", "D' R' F': R2, E", "R' U R U R U R' U' R' U'", "r: L E' L', U'", "U' E': R'/E'", "S, L' F' L", "u': R/E", "R' F': R S' R', F2", "U' R D: R'/S'", "U: L2, S"],
    "DB": ["U2, M", "R U R': U/M", "U l: U/R' E R", "U D: L'/E'", "D': S, L' F' L", "U' D': R/E", "D': S', R' F R", "M'/U R' U'", "U': R' B R, S", "M'/U R U'", "U: l U l', S", "U' D': R'/E'", "U' R' U, M2", "D: S, L F' L'", "M'/U' L' U", "U: L B' L', S'", "M'/U' L U", "M' U2 M' U2 M2", "U' R D: R/S'", "U' D R D R' D' R' D' R' D R U"],
    "DL": ["U: L2, S'", "L U L' U' L' U' L' U L U", "L U': L'/S'", "U: L'/E'", "U' L F: L'/S'", "U2 L' U L U L U L' U' L' U", "l': R' E R, U", "u: L'/E'", "S', R F R'", "U E: L/E", "U D: R' F' R, S", "L U' L' U' L' U' L U L U", "D L F: L2, E'", "U: L/E", "S, L F' L'", "U E: L'/E'", "u: L/E", "L: F/L' S L", "U': R2, S'", "U' R' D' R D R D R D' R' U D'"],
};

var ufr_corners = {
    "UBL": ["R D R': U'/R D' R'", "R' D' R U': U', R' D R", "l' D': U/R D R'", "D: U'/R D R'", "D': U'/R D' R'", "R' U D R: R U' R', D'", "U'/R D R'", "R' D' R, U2", "R' D: U/R D R'", "D': U'/R D R'", "D: U'/R D' R'", "F: U2, R' D' R", "R' D R, U2", "U'/R D' R'", "R F' R': U'/R D R'", "U' R' D R: R D' R', U2", "R D' R': R' D R, U2", "R' D' U' R: R U' R', D"],
    "UBR": ["R D R': U/R D' R'", "R' D' R: U/R' D R", "R: U2, R D R'", "D': R' D R, U", "D: R' D' R, U", "U', R D R'", "R' D' R, U", "R': R' D' R, U2", "R' D2 R, U", "D: U', R D' R'", "R: U, R D R'", "R': R' D' R, U'", "R' D R, U", "U', R D' R'", "F2, U R' U' R", "R' D R U' R D' R', U", "U', R D' R' U R' D R", "R' B: D', R U R'"],
    "UFL": ["R' D' R U': R' D R, U'", "R' D' R U': R' D R, U2", "D': R' D R, U'", "D: R' D' R, U'", "U' R': U2, R' D' R", "U': R D R', U'", "R' D' R, U'", "R' D': U', R' D R", "U' R': U', R' D' R", "D: R' D R, U'", "D': R' D' R, U'", "R U R': U2, R' D' R", "R' D R, U'", "U': R D' R', U'", "R' U' R: F2, R' U R U'", "R' D R U' R D' R', U'", "R D' R': R' D R, U'", "R' D' R: R U' R', D"],
    "LUB": ["R: R D R', U", "R U R': R' D' R, U2", "l': U/R D' R'", "R U R': R' D' R, U'", "R U: R' D R, U", "R: R2 D R2 D' R2, U", "U' R: R U' R', D'", "U R' U2: R D R', U", "U R': U', R' D' R", "U D R': U', R' D R", "R U: R' D' R, U", "L, U' R' U", "U R': U', R' D R", "R D': R D R', U", "D' R: R D' R', U", "U R' D': U', R' D' R", "D R: R D' R', U", "R: R D' R', U"],
    "LUF": ["F: R' D' R, U2", "R': U', R' D' R", "R: F, R' U R U'", "D R' U': D', R U R'", "R U' D' R': D, R' U R", "R': U'/R' D' R", "R' U': D', R U R'", "R' F: R U R', D", "R' U': R' D' R, U'", "D R' U': D, R U R'", "F: D', R U R'", "U' R' U, L", "R' U': D, R U R'", "U' R U': D', R' U R", "U' R' U: R U' R', D", "R U' R': R' D' R, U2", "R U' R': D, R' U R", "R2 D2: R U' R', D"],
    "LDF": ["U2, R' D R", "U, R' D R", "U', R' D R", "D R': F2, R D' R' D", "D, U R U' R'", "U R U: R' D R, U2", "U: D/R U' R'", "U R': D/R U' R'", "R' U: R U' R', D", "U' R' D: U', R' D' R", "U D: R U' R', D", "U R': U/R' D R", "U R': R' D R, U'", "R' U': R U R', D", "D R': F', R D' R' D", "U D R D': U', R' D R", "U R: D, R U' R'", "D R: R' U R U', F2"],
    "LDB": ["U/R D' R'", "R D' R', U'", "U2: R D' R', U", "R D: U'/R' D R", "U R U': R D' R', U'", "D2: R U R', D'", "U R: R D' R', U2", "R: D'/R' U' R", "D2, R U R'", "U' R U: R' U' R, D'", "U2 R: R D' R', U", "D2: R U R', D", "R D': U, R D R'", "U' R U': R' U R, D'", "D R': R D' R' D, F'", "D' R U': D/R' U R", "D2 R: R D' R', U'", "R D' R': R' D R, U"],
    "FUL": ["l' D': U'/R D R'", "R: R D R', U2", "D' R' D: F2, D' R D R'", "R: U/R' D R", "R': U', R2 D' R2 D R2", "R D': U/R' D R", "D R: U/R' D' R", "R D': U/R' D' R", "R U R' D: U/R D R'", "D R' D: F2, D' R D R'", "R: U/R' D' R", "l': U'/R D' R'", "R' D: F2, D' R D R'", "R D: U/R' D R", "R D: U/R' D' R", "D' R D: U/R' D' R", "D R: R D' R', U2", "R: R D' R', U2"],
    "FDR": ["D: U/R D R'", "D': U, R' D R", "D': U', R' D R", "R': F2, R D' R' D", "R': F', R D' R' D", "U' R': U/R D R'", "U R U' R', D'", "D' R' U: R U' R', D", "D R' U: R' D' R, U", "U R U' R', D2", "D R: D/R' U' R", "R U R': U', R' D' R", "U R U': F, U R' U' R", "U R U' R', D", "U R U': U', R D' R'", "U R U': F2, U R' U' R", "U R D': U', R' D R", "R' D' R: R U R', D"],
    "FDL": ["D': U/R D' R'", "D: U, R' D' R", "D: U', R' D' R", "R: U'/R' D R", "D' R' D: F', D' R D R'", "U D' R: R D' R', U2", "R D2: R' U' R, D'", "D, R U R'", "U R' U': D, R U R'", "D R': D, R' U R", "D' R: D'/R' U' R", "D/R U R'", "R U2: R' D R, U'", "D R' U': R U R', D'", "D: R U R', D", "R U' R': R' D R, U2", "D R: R D' R', U'", "D R D: U, R' D' R"],
    "RUB": ["R' U D R: D', R U' R'", "U' R': R' D' R, U2", "R': R2 D' R2 D R2, U'", "U' R': U'/R D R'", "U R D: U'/R' D' R", "U' D R': U'/R D' R'", "R': D', R2 U R2 U' R2", "U R: U2, R D R'", "U' R': U'/R D' R'", "U D R: U2, R D' R'", "R: U, R2 D R2 D' R2", "R U' D' R': R' U R, D", "U R: U'/R' D R", "U R: U2, R D' R'", "U' R': R' D R, U2", "U' D' R': R' D R, U2", "R': R2 D' R2 D R2, U", "U' D R': R' D R, U2"],
    "RDB": ["U/R D R'", "R D R', U'", "U2: R D R', U", "R D': U'/R' D R", "D', U R U' R'", "R D: R' U' R, D", "U' D R': U/R D' R'", "R' U: D', R U R'", "U' R U: R' U' R, D", "R' U: R' D' R, U", "U' R' U' R, D'", "U' R: D', R U' R'", "R': U/R' D' R", "U: D'/R U' R'", "R: D/R' U' R", "U' R': R' D R, U", "D' R: R' U R U', F2", "U' R': R' D2 R, U"],
    "RDF": ["U2, R' D' R", "U, R' D' R", "U', R' D' R", "D R: U'/R' D' R", "R U R', D", "R': R2 U R2 U' R2, D'", "R' U: R U R', D'", "R' U: R U' R', D'", "R': D, R' U R", "U R' D': R U' R', D'", "R U R', D'", "U R' U': R D R', U'", "R' U': R U R', D'", "U R': D'/R U' R'", "R U R', D2", "R D: U, R' D' R", "R: U, R' D R U' R D' R'", "R: R D' R', U'"],
    "BUR": ["R' D: U'/R D R'", "R' D': R' D R, U'", "R D': U'/R' D' R", "D' R' U: D, R U' R'", "U R' U': R U R', D", "U' R U: D, R' U' R", "R' U: D', R U' R'", "R, U' L' U", "D R' U: D, R U' R'", "R U': R' U R, D", "U R': R' D' R, U'", "R' F: D, R U R'", "R' U: D, R U' R'", "U' R U: D', R' U' R", "D' R U': R' U R, D'", "U R' U': R U R', D'", "D R U': R' U R, D'", "R U': R' U R, D'"],
    "BUL": ["R': U2, R' D' R", "U' R': R' D' R, U'", "R U R' D: U'/R D R'", "D R' U2: R' D' R, U'", "D R': R' U R, D", "U R: R D R', U2", "R' U2: R' D' R, U'", "R': R' U R, D", "U' L' U, R", "U' R' U': R D' R', U'", "D' R': R' U R, D", "R' U': U', R' D' R", "U' R' D: R' D' R, U'", "U2 R: U, R D' R'", "U' R': R' D R, U'", "U' D' R': R' D R, U'", "U R: D', R U' R'", "R2 U: D', R' U' R"],
    "BDL": ["D': U/R D R'", "U, R' D2 R", "D: U', R' D R", "D2 R': F2, R D' R' D", "D2, U R U' R'", "D' R: D/R' U' R", "U' R': U/R D' R'", "D', U' R' U' R", "U R' D2: R U' R', D", "D R' U: R U' R', D", "U' R' U2: R D' R', U", "U': R', U' L U", "U D R': R' D R, U'", "D R' U': R U R', D", "U D2: R U' R', D'", "U' D' R': R' D2 R, U", "U' D' R': R' D R, U", "U R: D2, R U' R' "],
    "BDR": ["D: U/R D' R'", "D: R D' R', U'", "D': U', R' D' R", "R: U'/R' D' R", "D R: D'/R' U' R", "D'/R U R'", "U D R: R D' R', U2", "D', R U R'", "R U': D, R' U R", "D' R': D, R' U R", "U2: L, U R' U'", "R U2: R' D' R, U'", "F: R U R', D'", "U R': U'/R' D R", "D': R U R', D'", "D' R: R D' R', U'", "D' R D: U, R' D' R", "R U': D/R' U R"],
    "DFL": ["R F' R': U/R D R'", "U R' U' R, F2", "U': F2, U R' U' R", "R D: U'/R' D' R", "R: F2, R' U R U'", "U' R': U2, R' D R", "U' R': U, R' D R", "R D: R' D' R, U", "D' R U': D', R' U R", "U' R': U', R' D R", "U' D' R': U, R' D2 R", "D' R: U', R D' R'", "D' R: U, R D' R'", "U' R' U: D, R U' R'", "D' R U': D'/R' U R", "D, R2 U R2 U' R2", "R U' R': D2, R' U R", "R U' D2: R' U R, D"],
    "DFR": ["U R' D R: R D' R', U2", "U, R' D R U' R D' R' ", "U', R' D R U' R D' R' ", "D' R D: U'/R' D' R", "R U' R': U2, R' D R", "U' D' R': U2, R' D R", "D' R: F2, R' U R U'", "U R' U': D', R U R'", "U' D' R': U', R' D R", "U' D' R': U, R' D R", "D' R D: R' D' R, U", "U R' D': R' D' R, U'", "R U' R': U2, R' D' R", "U D R D': R' D R, U'", "D2 R: U', R D' R'", "R2 U R2 U' R2, D", "R2 U R2 U' R2, D'", "R U' R': U/R D' R'"],
    "DBR": ["R D' R': U2, R' D R", "R D' R' U R' D R, U'", "R D' R': U', R' D R", "D R: U2, R D' R'", "U R D': R' D R, U'", "D R: U', R D' R'", "R': U, R2 D' R2 D R2", "R: R' D R U' R D' R', U", "D R U': D', R' U R", "U R: R U' R', D'", "U R: R U' R', D2", "D R: U, R D' R'", "R U' R': R' U R, D", "U R: R U' R', D", "R D' R': U, R' D R", "R U' R': R' U R, D2", "D', R2 U R2 U' R2", "R U' R': R' U R, D'"],
    "DBL": ["R' U' D' R: D, R U' R'", "R' B: R U R', D'", "R' D' R: D, R U' R'", "R: U2, R D' R'", "R' D' R: D, R U R'", "D R D: R' D' R, U", "U' D R': U2, R' D R", "U' R': U, R' D2 R", "R: U', R D' R'", "R U': D', R' U R", "R2 U: R' U' R, D'", "R U': D'/R' U R", "R: U, R D' R'", "R2 D': R U' R', D'", "D R: F2, R' U R U'", "R U' D': R' U R, D'", "R U' R': U'/R D' R'", "R U' R': D', R' U R"],
};

var _2co = {
    "UFR": ["U2 R' D R D' R' D R U2 R' D' R D R' D' R!U2, R' D R D' R' D R", "R' D R D' R' D R U2 R' D' R D R' D' R U2!R' D R D' R' D R, U2", "U R' D R D' R' D R U' R' D' R D R' D' R!U, R' D R D' R' D R", "R' D R D' R' D R U R' D' R D R' D' R U'!R' D R D' R' D R, U", "U' R' D R D' R' D R U R' D' R D R' D' R!U', R' D R D' R' D R", "R' D R D' R' D R U' R' D' R D R' D' R U!R' D R D' R' D R, U'", "R' D R U R' U' R U R' D' R U' R' U R U'!R': D, R U R' U' R U R'", "U R' U' R U R' D R U' R' U R U' R' D' R!R': R U R' U' R U R', D", "R' D' R U R' U' R U R' D R U' R' U R U'!R': D', R U R' U' R U R'", "U R' U' R U R' D' R U' R' U R U' R' D R!R': R U R' U' R U R', D'", "U' R D R' U R U' R' U R D' R' U' R U R'!U' R: D, R' U R U' R' U R", "R U' R' U R D R' U' R U R' U' R D' R' U!U' R: R' U R U' R' U R, D", "U' R D' R' U R U' R' U R D R' U' R U R'!U' R: D', R' U R U' R' U R", "R U' R' U R D' R' U' R U R' U' R D R' U!U' R: R' U R U' R' U R, D'"],
    "Floating UU": ["U R D R' D' R D R' U' R D' R' D R D' R'!U, R D R' D' R D R'", "U2 R' D R D' R' D R U R' D' R D R' D' R U!U2: R' D R D' R' D R, U", "R D R' D' R D R' U R D' R' D R D' R' U'!R D R' D' R D R', U", "U' R' D R D' R' D R D' U' D R' D' R D R' D' R U2!U': R' D R D' R' D R D', U'", "U R' D R D' R' D R U2 R' D' R D R' D' R U!U/R' D R D' R' D R", "U' R' D R D' R' D R U2 R' D' R D R' D' R U'!U'/R' D R D' R' D R"],
    "Floating UD": ["U' D R' D' R U' R' D R D' R' D R U R' D' R U!U' R' D R: R' D' R D R' D' R, U'", "R' U R D R' U' R U R' U' R D' R' U R U'!R' U R: D, R' U' R U R' U' R", "U R D R' U' R U R' U' R D' R' U R U' R'!U R: D, R' U' R U R' U' R", "U R D' R' U' R U R' U' R D R' U R U' R'!U R: D', R' U' R U R' U' R", "U' R' D R U' R' D' R D R' D' R U R' D R D' U!U' R' D R: U', R' D' R D R' D' R", "U R' U' R D R' U R U' R' U R D' R' U' R!R' U R: R' U' R U R' U' R, D", "R U R' U' R D R' U R U' R' U R D' R' U'!U R: R' U' R U R' U' R, D", "R U R' U' R D' R' U R U' R' U R D R' U'!U R: R' U' R U R' U' R, D'", "U R' D R U' R' U R U' R' D' R U R' U' R!U R': D, R U' R' U R U' R'", "U R' D' R U' R' U R U' R' D R U R' U' R!U R': D', R U' R' U R U' R'", "U R U' R' U R D R' U' R U R' U' R D' R'!R: R' U R U' R' U R, D", "U R U' R' U R D' R' U' R U R' U' R D R'!R: R' U R U' R' U R, D'", "R' U R U' R' D R U R' U' R U R' D' R U'!U R': R U' R' U R U' R', D", "R' U R U' R' D' R U R' U' R U R' D R U'!U R': R U' R' U R U' R', D'", "R D R' U R U' R' U R D' R' U' R U R' U'!R: D, R' U R U' R' U R", "R D' R' U R U' R' U R D R' U' R U R' U'!R: D', R' U R U' R' U R", "R' U' R U R' D R U' R' U R U' R' D' R U!U' R': R U R' U' R U R', D", "R' U' R U R' D' R U' R' U R U' R' D R U!U' R': R U R' U' R U R', D'", "U' R U R' D' R U' R' U R U' R' D R U R'!R U' R': R U R' U' R U R', D'", "D R' U' R U R' D R U' R' U R U' R' D' R U D'!U' D R': R U R' U' R U R', D", "U' R' D R U R' U' R U R' D' R U' R' U R!U' R': D, R U R' U' R U R'", "U' R' D' R U R' U' R U R' D R U' R' U R!U' R': D', R U R' U' R U R'", "R U' R' D' R U R' U' R U R' D R U' R' U!R U' R': D', R U R' U' R U R'", "D U' R' D R U R' U' R U R' D' R U' R' U R D'!U' D R': D, R U R' U' R U R'"],
    "Floating DD": ["R U' R' U R U' R' D R U R' U' R U R' D'!R U' R' U R U' R', D", "D' R U' R' U R U' R' D2 R U R' U' R U R' D'!D'/R U' R' U R U' R'", "D2 R U' R' U R U' R' D' R U R' U' R U R' D'!D2: R U' R' U R U' R', D'", "D R U' R' U R U' R' D' R U R' U' R U R'!D, R U' R' U R U' R'", "D R U' R' U R U' R' D2 R U R' U' R U R' D!D/R U' R' U R U' R'", "D R U' R' U R U' R' D R U R' U' R U R' D2!D: R U' R' U R U' R', D", "D' R U' R' U R U' R' D R U R' U' R U R'!D', R U' R' U R U' R'", "D2 R U' R' U R U' R' D2 R U R' U' R U R'!D2, R U' R' U R U' R'", "R U' R' U R U' R' D' R U R' U' R U R' D!R U' R' U R U' R', D'", "R U' R' U R U' R' D2 R U R' U' R U R' D2!R U' R' U R U' R', D2", "D' R' U' R U R' U' R D R' U R U' R' U R!D', R' U' R U R' U' R", "R' U' R U R' U' R D' R' U R U' R' U R D!R' U' R U R' U' R, D'"],
}

var _3co = {
    "UU": ["R U R2' U' R2 U2 R' S R2 S' R' U' R U'", "U2': R U R2' U' R2 U2 R' S R2 S' R' U' R U'", "U: R' U' R2 U R2' U2' R S R2' S' R U R' U ", "U': R' U' R2 U R2' U2' R S R2' S' R U R' U ", "U': R U R2' U' R2 U2 R' S R2 S' R' U' R U'", "R' U' R2 U R2' U2' R S R2' S' R U R' U "],
    "UD": ["D: R' D' R, U2 + U' R': U', R' D R", "R' D' R, U2 + U' D' R': U', R' D R", "U/R D R' + D R: R D' R', U", "D': U/R D R' + R: R D' R', U", "U' R': R' D R, U' + D: U2, R' D' R", "U' D' R': R' D R, U' + U2, R' D' R", "D R: U, R D' R' + U'/R D R'", "R: U, R D' R' + D': U'/R D R'", "R' U: D, R U' R' + D: U, R' D' R", "D' R' U: D, R U' R' + U, R' D' R", "R D R', U' + D R U': R' U R, D'", "D': R D R', U' + R U': R' U R, D'", "D: R' D' R, U + R' U: R U' R', D", "R' D' R, U + D' R' U: R U' R', D", "D R U': D', R' U R + U', R D R'", "R U': D', R' U R + D': U', R D R'", "U' R' U: D, R U' R' + D: R' D' R, U'", "U' D' R' U: D, R U' R' + R' D' R, U'", "U': R D R', U' + U' D R U': R' U R, D'", "U' D': R D R', U' + U' R U': R' U R, D'", "D: U', R' D' R + U' R' U: R U' R', D", "U', R' D' R + U' D' R' U: R U' R', D", "U' D R U': D', R' U R + U': U', R D R'", "U' R U': D', R' U R + U' D': U', R D R'"],
    "DD": ["R D: U, R' D' R + U: D, R U' R'", "U: D'/R U' R' + D R: R D' R', U'", "D R D: U, R' D' R + U D: D, R U' R'", "U: R U' R', D + R D: R' D' R, U", "D R: U', R D' R' + U: D/R U' R'", "U D: R U' R', D + D R D: R' D' R, U", "R U R', D' + U R D': R' D R, U'", "U: D2, R U' R' + R: R D' R', U'", "U R D': U', R' D R + D', R U R'", "R: U', R D' R' + U: R U' R', D2", "R D' R': U, R' D R + R U': D'/R' U R", "R U': D/R' U R + R D' R': R' D R, U"],
}

var _2eo = {
    "UF": ["U': S, R' F' R + U2, M'!U' S R' F' R S' R' F R U' M' U2 M", "R' E2 R2 E' R', U'!R' E2 R2 E' R' U' R E R2 E2 R U", "L E2 L2 E L, U!L E2 L2 E L U L' E' L2 E2 L' U'", "U2, M' + U': S, R' F' R!U2 M' U2 M U' S R' F' R S' R' F R U", "U2 M U': S, R' F' R + U2, M!U2 M U' S R' F' R S' R' F R U' M'", "L E' L', U + U, L' E2 L!L E' L' U L E L2 E2 L U' L' E2 L", "R' E R, U' + U', R E2 R'!R' E R U' R' E' R2 E2 R' U R E2 R'", "U/R' E' R + U': S, R2!U R' E' R U2 R' E R S R2 S' R2 U", "U'/L E L' + U: S', L2!U' L E L' U2 L E' L' S' L2 S L2 U'", "L' E L, U + U, L E2 L'!L' E L U L' E' L2 E2 L' U' L E2 L'", "R E' R', U' + U', R' E2 R!R E' R' U' R E R2 E2 R U R' E2 R"],
    "UB": ["U, R' E2 R2 E' R'!U R' E2 R2 E' R' U' R E R2 E2 R", "U', L E2 L2 E L!U' L E2 L2 E L U L' E' L2 E2 L'", "M', U2 + U: S, R' F' R!M' U2 M U' S R' F' R S' R' F R U'", "M U': S, R' F' R + M, U2!M U' S R' F' R S' R' F R U' M' U2", "L' E2 L, U' + U', L E' L'!L' E2 L U' L' E2 L2 E' L' U L E L'", "R E2 R', U + U, R' E R!R E2 R' U R E2 R2 E R U' R' E' R", "U'/R' E' R + U: S, R2!U' R' E' R U2 R' E R S R2 S' R2 U'", "U/L E L' + U': S', L2!U L E L' U2 L E' L' S' L2 S L2 U", "L E2 L', U' + U', L' E L!L E2 L' U' L E2 L2 E L U L' E' L", "R' E2 R, U + U, R E' R'!R' E2 R U R' E2 R2 E' R' U' R E R'"],
    "UR": ["S, R' F' R + U'/M'!S R' F' R S' R' F R U' M' U2 M U'", "U'/M' + S, R' F' R!U' M' U2 M U' S R' F' R S' R' F R", "U' M U': S, R' F' R + U'/M!U' M U' S R' F' R S' R' F R U' M' U'", "U: L E' L', U + U2: L' E2 L, U'!U L E' L' U L E L2 E2 L U' L' E2 L U'", "U, R' E R + R E2 R', U!U R' E R U' R' E' R2 E2 R' U R E2 R' U'", "R' F' R, S' + S': U'/M'!R' F' R S' R' F R U' M' U2 M U' S", "L E L', U2 + U2: S', L2!L E L' U2 L E' L' S' L2 S L2 U2", "U: L' E L, U + U2: L E2 L', U'!U L' E L U L' E' L2 E2 L' U' L E2 L' U'", "U, R E' R' + R' E2 R, U !U R E' R' U' R E R2 E2 R U R' E2 R U'"],
    "UL": ["U/M' + S', L F L'!U M' U2 M U S' L F L' S L F' L'", "U M U': S, R' F' R + U: M, U2!U M U' S R' F' R S' R' F R U' M' U", "U', L E' L' + L' E2 L, U'!U' L E' L' U L E L2 E2 L U' L' E2 L U", "U': R' E R, U' + U2: R E2 R', U!U' R' E R U' R' E' R2 E2 R' U R E2 R' U", "R' E' R, U2 + U2: S, R2!R' E' R U2 R' E R S R2 S' R2 U2", "L F L', S + S: U/M'!L F L' S L F' L' U M' U2 M U S'", "U', L' E L + L E2 L', U'!U' L' E L U L' E' L2 E2 L' U' L E2 L' U", "U': R E' R', U' + U2: R' E2 R, U!U' R E' R' U' R E R2 E2 R U R' E2 R U"],
    "DF": ["M2 U': S, R' F' R + M2: U2, M'!M2 U' S R' F' R S' R' F R U' M' U2 M'", "R: U'/M' + R S R', F'!R U' M' U2 M U' S R' F' R S' R' F", "M': R' E R, U' + M': U', R E2 R'!M' R' E R U' R' E' R2 E2 R' U R E2 r'", "r: L E' L', U + r U r', S2!r L E' L' U L E L' r' S2 r U' r' S2", "l': R' E R, U' + l' U' l, S2!l' R' E R U' R' E' R l S2 l' U l S2", "R': U'/M' + R': S, R' F' R!R' U' M' U2 M U' S R' F' R S' R' F R2", "r: E', R' U' R + M': U', R' E2 R!r E' R' U' R E R2 E2 R U R' E2 R M"],
    "DB": ["M: L' E2 L, U' + M: U', L E' L'!M L' E2 L U' L' E2 L2 E' L' U L E l'", "M: R E2 R', U + M: U, R' E R!M R E2 R' U R E2 R2 E R U' R' E' r", "S2, r' U' r + r': U', r' S' r!S2 r' U' r S2 r2 S' r U r' S r2", "S2, l U l' + l: U, l S l'!S2 l U l' S2 l2 S l' U' l S' l2", "l: E2, L' U' L + M: U', L' E L!l E2 L' U' L E2 L2 E L U L' E' L M'", "r': E2, R U R' + M: U, R E' R'!r' E2 R U R' E2 R2 E' R' U' R E R' M'"],
    "FR": ["R S R' F2: R2, E + R S R', F2!R S R' F2 R2 E R2 E' R S' R' F2", "u: R/E + U E2: R/E'!u R E R2 E' R E' R E' R2 E R E2 U'", "L/E' + L F2 L', S!L E' L2 E L2 F2 L' S L F2 L' S'", "R2, E + R S' R', F2!R2 E R2 E' R S' R' F2 R S R' F2", "R2, E' + E': F2, R S' R'!R2 E' R2 F2 R S' R' F2 R S R' E"],
    "FL": ["R'/E + R' F2 R, S'!R' E R2 E' R2 F2 R S' R' F2 R S", "u': L'/E' + U' E2: L'/E!u' L' E' L2 E L' E L' E L2 E' L' E2 U", "E, R2 + F2, R S' R'!E R2 E' R2 F2 R S' R' F2 R S R'", "L2, E' + L' S L, F2!L2 E' L2 E L' S L F2 L' S' L F2"],
    "DR": ["U': R2, S' + R F R', S'!U' R2 S' R2 S U R F R' S' R F' R' S", "U' E2: R/E + u': R/E'!U' E2 R E R2 E' R E' R E' R2 E R u", "l: R' E' R, U2 + l U2: S, R2!l R' E' R U2 R' E R S R2 S' R2 U2 l'"],
    "DL": ["r': L E L', U2 + r' U2: S', L2!r' L E L' U2 L E' L' S' L2 S L2 U2 r", "U E2: L'/E' + u: L'/E!U E2 L' E' L2 E L' E L' E L2 E' L' u'"],
    "BR": ["E' R2: F2, R S' R' + E', R2!E' R2 F2 R S' R' F2 R S R' E R2"],
};

var ltct_zeph = {
    "UU UBL": ["R2 U R' D' R U R' D R' U' R2 U' R2' U'!U2' R U R' U2 R' D' R U R' D R2 U' R' U R U' R'", "R2' D' R U R' D R U R U' R' U' R U'", "U' R2 D R' U' R D' R' U' R' U R U R' U2'", "U R' U' R U2 R D R' U' R D' R2' U R U' R' U R U!U R' U2 R U2' R2' D' R U2 R' D R2 U' R' U R U2'", "U R' D' R U' R' D R U2 R U R' U2' R U R' U'", "R U R' U' R U R2' D' R U' R' D R U2 R U' R' U2", "L' U L U2' L' U L U2' L D L' U' L D' L'!U2' R' U R U2' R' U R U2 R D R' U' R D' R' U2", "U2 R U' R' U' R U R D R' U R D' R2' U", "U R' U R U R' U' R' D' R U' R' D R2", "U R U' R' U2 R U' R' U2 R' D' R U R' D R U'", "U' R' U' R U R' U' R2 D R' U R D' R' U2 R' U R U'!U2 R' U' R U R2' D' R U2 R' D R2 U2' R' U2 R U'", "L D L' U L D' L' U2' L' U' L U2 L' U' L!U2 R D R' U R D' R' U2 R' U' R U2 R' U' R U2"],
    "UU UBR": ["U R U R2' D' R U R' D R2 U2' R'", "U' R D R' U' R D' R2' U R U' R' U' R U R' U' R", "U R' U2 R' D' r U2 r' D R2 U2'", "U' D' R2 U R' U' R' U R' U' D R' U R!U R U R' U' R B2 R' U2 R U2' R B2 R2'", "U R' D' R U R' D R2 U R' U2' R U R' U'", "R U2 R' U' R2 D R' U' R D' R2' U'", "U R U R' U' R U R2' D' R U2 R' D R2 U2' R' U", "U2' R2' D' r U2 r' D R U2 R U'", "R' U R U' R' U R U R' U' R2 D R' U R D' R' U", "U R U' R' U2 R U' R2' D' R U' R' D R U'", "R' U' R U D' R U' R U R U' R2' U D!R2 B2 R' U2 R' U2' R B2 R' U R U' R' U'", "U2 f' L F L' U2' L' U2 L U2' S U'!U' R U2' R2' D' R U2 R' D R2 U' R' U R U' R' U'"],
    "UU UFL": ["R' D' R U R' D R2 U' R' U R U R' U' R U R' U", "U2' R2' D' R U' R' D R2 U' R' U2 R U", "R2' U' R U R U' R U D' R U' R' U D!U2 R' U' R U R' F2 R U2' R' U2' R' F2 R2 U!D R2' U' R U R U' R U D' R U' R' U", "U R' F' R U R' U' R' F R2 U' R' U2 R U", "L' U L U2' L' U L2 D L' U L D' L'!U2' R' U R U2' R' U R2 D R' U R D' R' U2", "U' R U' R' U R U' R' U' R U R2' D' R U' R' D R", "U' f R' F' R U2 R U2' R' U2 S'", "U' D' R U R' U' D R' U R' U' R' U R2!U' R2' F2 R U2' R U2' R' F2 R U' R' U R U2'", "U' R' U2 R U R2' D' R U R' D R2 U2'", "R U R D R' U R D' R2' U' R U' R' U'!U2 R D R' U' R D' R2' U' R U2 R' U' R U2!L D L' U' L D' L2' U' L U2 L' U' L", "U' R' U2 R U R2' F' R U R U' R' F R U'", "U R U2' R' U' F' R U R' U' R' F R2 U' R'"],
    "UD UBL": ["U' D R U2' R' U R U R2' D' R U R' D R U D'", "U' R U2' R' U R U R2' D' R U R' D R U", "U' D' R U2' R' U R U R2' D' R U R' D R U D", "U L U2' L' U L2 D L' U L D' L2'", "D2 R' U2 R U' R2' D' R U' R' D R2 U' D2", "D R' U2 R U' R2' D' R U' R' D R2 U' D'", "R' U2 R U' R2' D' R U' R' D R2 U'", "D' R' U2 R U' R2' D' R U' R' D R2 U' D", "R' D R U2 R U R' U2 R U R2' D' R U'!U2 D R U R' U2 R2 D R' U R D' R2' U' D'", "D' R' D R U2 R U R' U2 R U R2' D' R U' D!U2 R U R' U2 R2 D R' U R D' R2' U'", "U R D R' U R D' R2' U R U2 R' U R U'", "U D' R D R' U R D' R2' U R U2 R' U R U' D", "U' D R' D' R U' R' D R2 U' R' U' R U2' R' U D'", "U' R' D' R U' R' D R2 U' R' U' R U2' R' U", "U' D' R' D' R U' R' D R2 U' R' U' R U2' R' U D", "L2 D L' U' L D' L2' U' L U2 L' U'", "U D2 R2' D' R U R' D R2 U R' U2 R D2", "U D R2' D' R U R' D R2 U R' U2 R D'", "U R2' D' R U R' D R2 U R' U2 R", "U D' R2' D' R U R' D R2 U R' U2 R D", "U R' D R2 U' R' U2 R U' R' U2 R' D' R", "U D R' U' R U2 R' U' R2 D R' U' R D' R' U' D'!U D' R' D R2 U' R' U2 R U' R' U2 R' D' R D", "U R' U' R U2 R' U' R2 D R' U' R D' R' U'", "U D' R' U' R U2 R' U' R2 D R' U' R D' R' U' D"],
    "UD UBR": ["D' R D' R' U2 R' U' R2 D r' U2 M' D", "U' R U' R' U R U2' r' R' F R F' M'!U' R U R' U' R2 U R' D R U' D' R2' D R U D'", "D R D' R' U2 R' U' R2 D r' U2 M' D'", "R D' R' U2 R' U' R2 D r' U2 M'", "L' U' L2 D l' U2 M U' L D' L' U'", "U2 D R' U' R2 D r' U2 M' U' R D' R' U D'", "U2 R' U' R2 D r' U2 M' U' R D' R' U", "U2 D' R' U' R2 D r' U2 M' U' R D' R' U D", "U2 D R U R' U' R' D' R U' R' D R2 U R' U' D'", "U2 R U R' U' R' D' R U' R' D R2 U R' U'", "U2 D' R U R' U' R' D' R U' R' D R2 U R' U' D", "U2 D2 R U R' U' R' D' R U' R' D R2 U R' U' D2", "D2 R B2 R' D r B2 r D r2' D", "D R B2 R' D r B2 r D r2' D2", "R B2 R' D r B2 r D r2' D'", "D' R B2 R' D r B2 r D r2'", "U L D L' U M' U2 l D' L2' U L", "U' D R D R' U M U2 r D' R2' U R U2' D'", "U' R D R' U M U2 r D' R2' U R U2", "U' D' R D R' U M U2 r D' R2' U R U2 D", "U D R U' R2' D' R U R' D R U R U' R' U2 D'", "U R U' R2' D' R U R' D R U R U' R' U2", "U D' R U' R2' D' R U R' D R U R U' R' U2 D", "U D2 R U' R2' D' R U R' D R U R U' R' U2 D2"],
    "UD UFL": ["U D R U R2' D' r U2 M U R' D R D'", "U R U R2' D' r U2 M U R' D R", "U D' R U R2' D' r U2 M U R' D R D", "U D2 R U R2' D' r U2 M U R' D R D2'", "U D2 R2' U R U2 R D r' U2 r U' D", "U D R2' U R U2 R D r' U2 r U' D2", "U R2' U R U2 R D r' U2 r U' D'", "U D' R2' U R U2 R D r' U2 r U'", "U2 D2 R' U R2 D R' U' R D' R' U' R' U R U' D2", "U2 D R' U R2 D R' U' R D' R' U' R' U R U' D'", "U2 R' U R2 D R' U' R D' R' U' R' U R U'", "U2 D' R' U R2 D R' U' R D' R' U' R' U R U' D", "D R' D' R U' M' U2 r' D R2 U' R' U' D'", "R' D' R U' M' U2 r' D R2 U' R' U'", "D' R' D' R U' M' U2 r' D R2 U' R' U' D", "D2 R' D' R U' M' U2 r' D R2 U' R' U' D2", "U D' r' U2 r D' R' U2 R' U' R2 U' D2", "U D2 r' U2 r D' R' U2 R' U' R2 U' D'", "U D r' U2 r D' R' U2 R' U' R2 U'", "U r' U2 r D' R' U2 R' U' R2 U' D", "U D2 R' U' R U R D R' U R D' R2' U' R U2 D2", "U D R' U' R U R D R' U R D' R2' U' R U2 D'", "U R' U' R U R D R' U R D' R2' U' R U2", "U D' R' U' R U R D R' U R D' R2' U' R U2 D"],
    "DU LDF": ["D' L U L' D L2 U2 L' U L U L2'", "U R2' U R U R' U2' R2 D R' U R U' D'", "U D' R2' U R U R' U2' R2 D R' U R U'", "U D2 R2' U R U R' U2' R2 D R' U R U' D", "U' D L D' L2' U' L U2 L' U' L2 D L' D'!U D' R D' R2' U' R U2 R' U' R2 D R' U2 D", "U' L D' L2' U' L U2 L' U' L2 D L'!D R' U2 R U' R' U2 R' D' R U R' D R2 U' D'", "R' U2 R U' R' U2 R' D' R U R' D R2 U'", "U R D' R2' U' R U2 R' U' R2 D R' U2", "L' U' L2 D l' U2 l D' L' U2'", "U2 D R' U' R2 D r' U2 r D' R' D'", "U2 R' U' R2 D r' U2 r D' R'", "U2 D' R' U' R2 D r' U2 r D' R' D", "U2 L' U2 L U' M F' L F l'", "U D R D R' U' R D' R2' U2' R U' R' U' R U' D'", "U R D R' U' R D' R2' U2' R U' R' U' R U'", "U D' R D R' U' R D' R2' U2' R U' R' U' R U' D", "U' D R' D' r U2 r' D R2 U' R' U' D'", "U' R' D' r U2 r' D R2 U' R' U'", "U' D' R' D' r U2 r' D R2 U' R' U' D", "U L' D' l U2' l' D L2 U' L' U", "D L' U' L D' L2' U' L U2 L' U' L2", "U D R2 U R2' D' r U2 r' D R U2 R' U' D'", "U R2 U R2' D' r U2 r' D R U2 R' U'", "U D' R2 U R2' D' r U2 r' D R U2 R' U' D"],
    "DU FDL": ["U2 R' D R2 U R' U2 R U R2' D' R U'", "U2 D' R' D R2 U R' U2 R U R2' D' R U' D", "L' D L2 U L' U2' L U L2' D' L U", "U2 D R' D R2 U R' U2 R U R2' D' R U' D'", "L2 U' L' U' L U2 L2' D' L U' L' D", "U D R' U' R D' R2' U2' R U' R' U' R2 U'", "U R' U' R D' R2' U2' R U' R' U' R2 U' D", "D L2 U' L' U' L U2 L2' D' L U' L'", "U R U R' D R2 U R' U2 R U R2' U' D'", "U D' R U R' D R2 U R' U2 R U R2' U'", "U D2 R U R' D R2 U R' U2 R U R2' U' D", "U D R U R' D R2 U R' U2 R U R2' U' D2", "U2' L D l' U2' l D' L2' U L", "D R D r' U2 r D' R2' U R U2 D'", "R D r' U2 r D' R2' U R U2'", "D' R D r' U2 r D' R2' U R U2 D", "U' D R U2' R' U M F R' F' r U' D'!U2 D R' D' R U R' D R2 U2' R' U R U R' U2 D'", "U' R U2' R' U M F R' F' r U'!U2 R' D' R U R' D R2 U2' R' U R U R' U2'", "U' D' R U2' R' U M F R' F' r U' D!U2 D' R' D' R U R' D R2 U2' R' U R U R' U2 D", "L' D' L U L' D L2 U2 L' U L U L'", "U D R U R2' D' r U2 r' D R U D'", "U R U R2' D' r U2 r' D R U", "U D' R U R2' D' r U2 r' D R U D", "U' L U L2' D' l U2' l' D L U'"],
    "DU DFL": ["D L D' L2' U L U2' L' U L2 D L' U D'", "L D' L2' U L U2' L' U L2 D L' U", "U R2' D' R U' R' D R U2 R U R' U2 R", "U2 R D' R2' U R U2 R' U R2 D R' U'", "U R' D R2 U' R' U2 R U' R2' D' R U2", "U D' R' D R2 U' R' U2 R U' R2' D' R U2 D", "U' L' D L2 U' L' U2' L U' L2' D' L", "U D R' D R2 U' R' U2 R U' R2' D' R U2 D'", "l F' L' F M' U L' U2 L U2'", "U D R' U R U R' U2' R2 D R' U R D' R' U' D'", "U R' U R U R' U2' R2 D R' U R D' R' U'", "U D' R' U R U R' U2' R2 D R' U R D' R' U' D", "U D R2 U' R' U2 R U' R2' D' R U' R' U'", "U R2 U' R' U2 R U' R2' D' R U' R' U' D", "U D' R2 U' R' U2 R U' R2' D' R U' R' U' D2", "U D2 R2 U' R' U2 R U' R2' D' R U' R' U' D'", "L2' U L U2' L' U L2 D L' U L D'", "U D R U2 R' D' r U2 r' D R2 U' R2' U' D'", "U R U2 R' D' r U2 r' D R2 U' R2' U'", "U D' R U2 R' D' r U2 r' D R2 U' R2' U' D", "U D r' F R F' M' U' R U2' R' U D'", "U r' F R F' M' U' R U2' R' U", "U D' r' F R F' M' U' R U2' R' U D", "L U' L' U' L U2 L2' D' L U' L' D L"],
    "DD LDF": ["D2 r' U2 r U' R' U R D' R' U2 R' U' R2 D'", "D r' U2 r U' R' U R D' R' U2 R' U' R2", "r' U2 r U' R' U R D' R' U2 R' U' R2 D", "D' r' U2 r U' R' U R D' R' U2 R' U' R2 D2", "R D R U R2' U D' R U R U R2' U' D R D' R U' R'", "L2' U' R' D' r U2 r' D R2 U' R' U' L2'!D' R D R U R2' U D' R U R U R2' U' D R D' R U' R' D", "L' U' D' R' D' r U2 r' D R2 U' R' U' D L!L' U D L' D' l U2' l' D L2 U' L' U D' L", "D' L' U' D' R' D' r U2 r' D R2 U' R' U' D L D!D R D R U R2' U D' R U R U R2' U' D R D' R U' R' D'", "D L' U' R' D' r U2 r' D R2 U' R' U' L D'", "L' U' R' D' r U2 r' D R2 U' R' U' L", "U' R2 U' R' U2 R' D' R U R' U' r U2 r' U D", "U' D' R2 U' R' U2 R' D' R U R' U' r U2 r' U D2", "U2 D R2' U R D' R U' R' D R U' R2' U R2 U' D'", "U2' R2' U R D' R U' R' D R U' R2' U R2 U'", "U2' D' R2' U R D' R U' R' D R U' R2' U R2 U' D", "U2 D2 R2' U R D' R U' R' D R U' R2' U R2 U' D2", "U' D' R' D' R U2 R U R2' D' r U2 r' D2 R U D", "L U' L D' L2' U' L U2 L' U' L2 D L2'", "U' D R' D' R U2 R U R2' D' r U2 r' D2 R U D'", "U' R' D' R U2 R U R2' D' r U2 r' D2 R U", "U D2 R2' U' R U2 R' U' R2 D R' U' R U' D", "U D R2' U' R U2 R' U' R2 D R' U' R U' D2", "U R2' U' R U2 R' U' R2 D R' U' R U' D'", "U D' R2' U' R U2 R' U' R2 D R' U' R U'"],
    "DD FDL": ["U D R U R U R' U' R' D' R U' R' D R2 U R2' U' D'", "U R U R U R' U' R' D' R U' R' D R2 U R2' U'", "D L2 U L' U2' L U L2' D' L U L'", "L2 U L' U2' L U L2' D' L U L' D!R D2 R' U2 R' U' R2 D r' U2 r D R'", "U R' U R' D R2 U R' U2 R U R2' D' R2 U'", "U D' R' U R' D R2 U R' U2 R U R2' D' R2 U' D", "U D2 R' U R' D R2 U R' U2 R U R2' D' R2 U' D2!U' L' U L' D L2 U L' U2' L U L2' D' L2 U", "U D R' U R' D R2 U R' U2 R U R2' D' R2 U' D'", "U D2 R U R' D' R D R U R' U2 R U R' D' R' U' D'", "U D R U R' D' R D R U R' U2 R U R' D' R' U'", "U R U R' D' R D R U R' U2 R U R' D' R' U' D", "U D' R U R' D' R D R U R' U2 R U R' D' R' U' D2", "D R2' U R U2 R D R' U' R U r' U2 r D2", "R2' U R U2 R D R' U' R U r' U2 r D'", "D' R2' U R U2 R D R' U' R U r' U2 r", "D2 R2' U R U2 R D R' U' R U r' U2 r D", "R U R' D R' U D' R2 U' R' U' R' U' D R2 U' R' D' R'", "L2' U R U R2' D' r U2 r' D R U L2'!D L' U' D L U L2' D' l U2' l' D L U' D' L D'", "L' U D' R U R2' D' r U2 r' D R U D L!L' U' D L U L2' D' l U2' l' D L U' D' L", "D' L' U' D L U L2' D' l U2' l' D L U' D' L D", "D L' U R U R2' D' r U2 r' D R U L D'", "L' U R U R2' D' r U2 r' D R U L", "D' L' U R U R2' D' r U2 r' D R U L D", "D2 L' U R U R2' D' r U2 r' D R U L D2'"],
    "DD DFL": ["R2' F' R2 U D' F' D F' U' F R2' F", "U R2' U' R2 U R' D' R U R' D R' U' R2 U2'", "U' D L2' U' L2 U L' D' L U L' D L' U' L2 D'", "U' L2' U' L2 U L' D' L U L' D L' U' L2", "U' D' R' D2 r U2 r' D R2 U' R' U2 R' D R U D", "L2 D' L2' U L U2' L' U L2 D L' U L'", "U' D R' D2 r U2 r' D R2 U' R' U2 R' D R U D'", "U' R' D2 r U2 r' D R2 U' R' U2 R' D R U", "U D' R' U R D' R2' U R U2 R' U R2 U' D2", "U D2 R' U R D' R2' U R U2 R' U R2 U' D'", "U D R' U R D' R2' U R U2 R' U R2 U'", "U R' U R D' R2' U R U2 R' U R2 U' D", "U D R2 U' R2' D' R U R' D R U R U' R' U' R' U' D'", "U R2 U' R2' D' R U R' D R U R U' R' U' R' U'", "L U' L' D L2 U' L' U2' L U' L2' D'", "D' L U' L' D L2 U' L' U2' L U' L2'", "U R2' D R2 U' R' U2 R U' R2' D' R U' R U'", "U D' R2' D R2 U' R' U2 R U' R2' D' R U' R U' D", "U D2 R2' D R2 U' R' U2 R U' R2' D' R U' R U' D2", "U D R2' D R2 U' R' U2 R U' R2' D' R U' R U' D'", "U D R D R U' R' U2 R U' R' D' R' D R U' R' U' D2", "U R D R U' R' U2 R U' R' D' R' D R U' R' U' D'", "U D' R D R U' R' U2 R U' R' D' R' D R U' R' U'", "U D2 R D R U' R' U2 R U' R' D' R' D R U' R' U' D"]
};

var ltct_james = {
    "UBL": ["R2 U R' D' R U R' D R' U' R2 U' R2' U'", "R' U2' R U2 R' F' R U R' U' R' F R2 U'", "R' D' R U' R' D R2 U2 R' U R U R' U2", "U R' U' R U2 R D R' U' R D' R2' U R U' R' U R U", "D U' R U2' R' U R U R2' D' R U R' D R U D'", "D2 R' U2 R U' R2' D' R U' R' D R2 U' D2", "U L U2' L' U L2 D L' U L D' L2'", "D' R' U2 R U' R2' D' R U' R' D R2 U' D", "U' R U2' R' U R U R2' D' R U R' D R U", "D R' U2 R U' R2' D' R U' R' D R2 U' D'", "D' U' R U2' R' U R U R2' D' R U R' D R U D", "R' U2 R U' R2' D' R U' R' D R2 U'"],
    "UBR": ["U R U R2' D' R U R' D R2 U2' R'", "R U R' U' R' U' F R f' R' U R S U'", "U R' U2 R' D' r U2 r' D R2 U2'", "U' R2 U R' U' R' U R3 U' D R' U R D'", "D' R D' R' U2 R' U' R2 D r' U2 M' D", "L' U' L2 D l' U2 M U' L D' L' U'", "R D' R' U2 R' U' R2 D r' U2 M'", "D' U2 R' U' R2 D r' U2 M' U' R D' R' U D", "U' R U' R' U R U2' r' R' F R F' M'", "D U2 R' U' R2 D r' U2 M' U' R D' R' U D'", "D R D' R' U2 R' U' R2 D r' U2 M' D'", "U2 R' U' R2 D r' U2 M' U' R D' R' U"],
    "UFL": ["R' D' R U R' D R2 U' R' U R U R' U' R U R' U", "U2 R' U' R2 D R' U' R D' R2' U2' R U", "R2' U' R U R U' R U D' R U' R' U D", "U R' F' R U R' U' R' F R2 U' R' U2 R U", "D U R U R2' D' r U2 M U R' D R D'", "D2 U R2' U R U2 R D r' U2 r U' D", "D2 U R U R2' D' r U2 M U R' D R D2'", "D' U R2' U R U2 R D r' U2 r U'", "U R U R2' D' r U2 M U R' D R", "D U R2' U R U2 R D r' U2 r U' D2", "D' U R U R2' D' r U2 M U R' D R D ", "U R2' U R U2 R D r' U2 r U' D'"],
    "LUB": ["U R' D' R U' R' D R U2 R U R' U2' R U R' U'", "R U R' U' R U R2' D' R U' R' D R U2 R U' R' U2", "L' U2 R U' L U R' U L' U L U", "U2 R U' R' U' R U2' R2' D' R U R' D R", "R' D R U2 R U R' U2 R U R2' D' R U'", "D U' R' D' R U' R' D R2 U' R' U' R U2' R' U D'", "D' U R D R' U R D' R2' U R U2 R' U R U' D", "L2 D L' U' L D' L2' U' L U2 L' U'", "U2' R U R' U2' R2 D R' U R D' R2' U'", "U' R' D' R U' R' D R2 U' R' U' R U2' R' U", "U R D R' U R D' R2' U R U2 R' U R U'", "D' U' R' D' R U' R' D R2 U' R' U' R U2' R' U D"],
    "LUF": ["U' R' U2 R U R2' D' R U R' D R2 U2'", "R U R D R' U R D' R2' U' R U' R' U'", "U' R' U2 R U R2' F' R U R U' R' F R U'", "S U2 R U2' R' U2 R' F R f' U", "D' U r' U2 r D' R' U2 R' U' R2 U' D2", "D2 U R' U' R U R D R' U R D' R2' U' R U2 D2", "U r' U2 r D' R' U2 R' U' R2 U' D", "U D' R' U' R U R D R' U R D' R2' U' R U2 D", "D2 U r' U2 r D' R' U2 R' U' R2 U' D'", "D U R' U' R U R D R' U R D' R2' U' R U2 D'", "D U r' U2 r D' R' U2 R' U' R2 U' ", "U R' U' R U R D R' U R D' R2' U' R U2"],
    "LDF": ["D' L U L' D L2 U2 L' U L U L2'", "D' U R D' R2' U' R U2 R' U' R2 D R' U2 D", "L' U' L2 D l' U2 l D' L' U2'", "U2 L' U2 L U' M F' L F l'", "D U' R' D' r U2 r' D R2 U' R' U' D'  ", "D L' U' L D' L2' U' L U2 L' U' L2", "D L' U' R' D' r U2 r' D R2 U' R' U' L D'", "D2 U R2' U' R U2 R' U' R2 D R' U' R U' D", "D2 r' U2 r U' R' U R D' R' U2 R' U' R2 D'", "D U2 R2' U R D' R U' R' D R U' R2' U R2 U' D'", "R D R U R2' U D' R U R U R2' U' D R D' R U' R'", "D' U' R' D' R U2 R U R2' D' r U2 r' D2 R U D"],
    "LDB": ["D U2 R' D R2 U R' U2 R U R2' D' R U' D'", "D L2 U' L' U' L U2 L2' D' L U' L'", "D U R U R' D R2 U R' U2 R U R2' U' D2", "D' R D r' U2 r D' R2' U R U2 D", "L' D' L U L' D L2 U2 L' U L U L'", "U' L U L2' D' l U2' l' D L U'", "R D2 R' U2 R' U' R2 D r' U2 r D R'", "D2 R2' U R U2 R D R' U' R U r' U2 r D", "D U R' U R' D R2 U R' U2 R U R2' D' R2 U' D'", "D' L' U' D L U L2' D' l U2' l' D L U' D' L D", "D' U R U R' D' R D R U R' U2 R U R' D' R' U' D2", "D2 L' U R U R2' D' r U2 r' D R U L D2'"],
    "FUL": ["U R U R' U R2 D R' U' R D' R' U' R'", "U' R U' R' U R U' R' U' R U R2' D' R U' R' D R", "U' f R' F' R U2 R U2' R' U2 S'", "U' D' R U R' U' D R3 U R' U' R' U R2", "D2 U2 R' U R2 D R' U' R D' R' U' R' U R U' D2", "D R' D' R U' M' U2 r' D R2 U' R' U' D'", "D' U2 R' U R2 D R' U' R D' R' U' R' U R U' D", "D2 R' D' R U' M' U2 r' D R2 U' R' U' D2", "D U2 R' U R2 D R' U' R D' R' U' R' U R U' D'", "R' D' R U' M' U2 r' D R2 U' R' U'", "U2 R' U R2 D R' U' R D' R' U' R' U R U'", "D' R' D' R U' M' U2 r' D R2 U' R' U' D"],
    "FDR": ["U R2' U R U R' U2' R2 D R' U R U' D'", "U' L D' L2' U' L U2 L' U' L2 D L'", "D U2 R' U' R2 D r' U2 r D' R' D'", "D U R D R' U' R D' R2' U2' R U' R' U' R U' D'", "U' R' D' r U2 r' D R2 U' R' U'", "D U R2 U R2' D' r U2 r' D R U2 R' U' D'", "L' U' R' D' r U2 r' D R2 U' R' U' L", "D U R2' U' R U2 R' U' R2 D R' U' R U' D2", "L2' U' R' D' r U2 r' D R2 U' R' U' L2'", "L U' L D' L2' U' L U2 L' U' L2 D L2'", "D r' U2 r U' R' U R D' R' U2 R' U' R2", "U2' R2' U R D' R U' R' D R U' R2' U R2 U'"],
    "FDL": ["U2 R' D R2 U R' U2 R U R2' D' R U'", "L2 U' L' U' L U2 L2' D' L U' L' D", "U R U R' D R2 U R' U2 R U R2' U' D'", "U2' L D l' U2' l D' L2' U L", "D U' R U2' R' U M F R' F' r U' D'", "D U R U R2' D' r U2 r' D R U D'", "D2 U R U R' D' R D R U R' U2 R U R' D' R' U' D'", "D L' U R U R2' D' r U2 r' D R U L D'", "D' R D2 R' U2 R' U' R2 D r' U2 r D R' D", "D R2' U R U2 R D R' U' R U r' U2 r D2", "U R' U R' D R2 U R' U2 R U R2' D' R2 U'", "R U R' D R' U D' R2 U' R' U' R' U' D R2 U' R' D' R'"],
    "RUB": ["U S' R' U' R f R' F' U R U R U' R'", "U R U' R' U2 R U' R2' D' R U' R' D R U'", "R' U' R U D' R U' R U R U' R2' U D", "U2 f' L F L' U2' L' U2 L U2' S U'", "U L D L' U M' U2 l D' L2' U L", "D U R U' R2' D' R U R' D R U R U' R' U2 D'", "D' U' R D R' U M U2 r D' R2' U R U2 D", "D2 U R U' R2' D' R U R' D R U R U' R' U2 D2", "D U' R D R' U M U2 r D' R2' U R U2 D'", "U R U' R2' D' R U R' D R U R U' R' U2", "U' R D R' U M U2 r D' R2' U R U2", "D' U R U' R2' D' R U R' D R U R U' R' U2 D"],
    "RDB": ["D' U R2' U R U R' U2' R2 D R' U R U'", "R' U2 R U' R' U2 R' D' R U R' D R2 U'", "U2 R' U' R2 D r' U2 r D' R'", "U R D R' U' R D' R2' U2' R U' R' U' R U'", "D' U' R' D' r U2 r' D R2 U' R' U' D", "U R2 U R2' D' r U2 r' D R U2 R' U'  ", "L' U' D' R' D' r U2 r' D R2 U' R' U' D L", "D U' R' D' R U2 R U R2' D' r U2 r' D2 R U D'", "r' U2 r U' R' U R D' R' U2 R' U' R2 D", "D' U2' R2' U R D' R U' R' D R U' R2' U R2 U' D", "U' R2 U' R' U2 R' D' R U R' U' r U2 r' U D", "U R2' U' R U2 R' U' R2 D R' U' R U' D'"],
    "RDF": ["D' U2 R' D R2 U R' U2 R U R2' D' R U' D", "D U R' U' R D' R2' U2' R U' R' U' R2' U'", "D' U R U R' D R2 U R' U2 R U R2 U'", "D R D r' U2 r D' R2' U R U2 D'", "U' R U2' R' U M F R' F' r U'", "U R U R2' D' r U2 r' D R U", "D U R U R' D' R D R U R' U2 R U R' D' R' U'", "L' U R U R2' D' r U2 r' D R U L", "D' U R' U R' D R2 U R' U2 R U R2' D' R2 U' D", "L2' U R U R2' D' r U2 r' D R U L2'", "U2 R2 U R' U2 R U R2' D' R U R' U2 D", "R2' U R U2 R D R' U' R U r' U2 r D'"],
    "BUR": ["U R' D' R U R' D R2 U R' U2' R U R' U'", "R U2 R' U' R2 D R' U' R D' R2' U'", "U S' U2' L' U2 L U2' L F' L' f U2'", "U2' R2' D' r U2 r' D R U2 R U'", "D U2 R U R' U' R' D' R U' R' D R2 U R' U' D'", "D2 R B2 R' D r B2 r D r2' D", "D2 U2 R U R' U' R' D' R U' R' D R2 U R' U' D2", "D' R B2 R' D r B2 r D r2'", "U2 R U R' U' R' D' R U' R' D R2 U R' U'", "D R B2 R' D r B2 r D r2' D2", "D' U2 R U R' U' R' D' R U' R' D R2 U R' U' D", "R B2 R' D r B2 r D r2' D'"],
    "BUL": ["U R' U R U R' U' R' D' R U' R' D R2", "U R U' R' U2 R U' R' U2 R' D' R U R' D R U'", "U' R' U' R U R' U' R2 D R' U R D' R' U2 R' U R U'", "U' L' U' L U' R U' L' U R' U2 L", "D2 U R2' D' R U R' D R2 U R' U2 R D2", "U R' D R2 U' R' U2 R U' R' U2 R' D' R", "D' R D R' U R D' R2 U R U R' U2' R D ", "D' U R' U' R U2 R' U' R2 D R' U' R D' R' U' D", "U D R2' D' R U R' D R2 U R' U2 R D'", "U D' R' D R2 U' R' U2 R U' R' U2 R' D' R D", "R D R' U R D' R2' U R U R' U2' R", "U R' U' R U2 R' U' R2 D R' U' R D' R' U'"],
    "BDL": ["D2 U R2' U R U R' U2' R2 D R' U R U' D", "U R D' R2' U' R U2 R' U' R2 D R' U2", "D' U2 R' U' R2 D r' U2 r D' R' D", "D' U R D R' U' R D' R2' U2' R U' R' U' R U' D", "U L' D' l U2' l' D L2 U' L' U", "D' U R2 U R2' D' r U2 r' D R U2 R' U' D", "D' r' U2 r U' R' U R D' R' U2 R' U' R2 D2", "D2 U2 R2' U R D' R U' R' D R U' R2 U R2 U' D2", "U R y R' U' R2 D r' U2 r D' R' U2 F' U'", "U' R' D' R U2 R U R2' D' r U2 r' D2 R U", "U' D' R2 U' R' U2 R' D' R U R' U' r U2 r' U D2", "D' U R2' U' R U2 R' U' R2 D R' U' R U'"],
    "BDR": ["L' D L2 U L' U2' L U L2' D' L U", "U R' U' R D' R2' U2' R U' R' U' R2 U' D", "D2 U R U R' D R2 U R' U2 R U R2' U' D", "R D r' U2 r D' R2' U R U2'", "D' U' R U2' R' U M F R' F' r U' D", "D' U R U R2' D' r U2 r' D R U D", "D2 U R' U R' D R2 U R' U2 R U R2' D' R2 U' D2", "L' U D' R U R2' D' r U2 r' D R U D L", "D L2 U L' U2' L U L2' D' L U L'", "D' R2' U R U2 R D R' U' R U r' U2 r", "U R U R' D' R D R U R' U2 R U R' D' R' U' D", "D' L' U R U R2' D' r U2 r' D R U L D"],
    "DFL": ["D L D' L2' U L U2' L' U L2 D L' U D'", "U R' D R2 U' R' U2 R U' R2' D' R U2", "l F' L' F M' U L' U2 L U2'", "D U R2 U' R' U2 R U' R2' D' R U' R' U'", "L2' U L U2' L' U L2 D L' U L D'", "D U r' F R F' M' U' R U2' R' U D'", "D' U R' U R D' R2' U R U2 R' U R2 U' D2", "D U R D R U' R' U2 R U' R' D' R' D R U' R' U' D2", "R2' F' R2 U D' F' D F' U' F R2' F", "D U R2 U' R2' D' R U R' D R U R U' R' U' R' U' D'", "D' U' R' D2 r U2 r' D R2 U' R' U2 R' D R U D", "R D2 r' U2 r D' R2 U R U2 R D' R'"],
    "DFR": ["L D' L2' U L U2' L' U L2 D L' U", "D' U R' D R2 U' R' U2 R U' R2' D' R U2 D", "D U R' U R U R' U2' R2 D R' U R D' R' U' D'", "U R2 U' R' U2 R U' R2' D' R U' R' U' D", "D U R U2 R' D' r U2 r' D R2 U' R2' U' D'", "U r' F R F' M' U' R U2' R' U", "D2 U R' U R D' R2' U R U2 R' U R2 U' D'", "U R D R U' R' U2 R U' R' D' R' D R U' R' U' D'", "L2 D' L2' U L U2' L' U L2 D L' U L'", "D' U R2' D R2 U' R' U2 R U' R2' D' R U' R U' D", "U R2' U' R2 U R' D' R U R' D R' U' R2 U2'", "U R2 U' R2' D' R U R' D R U R U' R' U' R' U'"],
    "DBR": ["U R2' D' R U' R' D R U2 R U R' U2 R", "U' L' D L2 U' L' U2' L U' L2' D' L", "U R' U R U R' U2' R2 D R' U R D' R' U'", "D' U R2 U' R' U2 R U' R2' D' R U' R' U' D2", "U R U2 R' D' r U2 r' D R2 U' R2' U' ", "D' U r' F R F' M' U' R U2' R' U D", "D U' R' D2 r U2 r' D R2 U' R' U2 R' D R U D'", "D2 U R2' D R2 U' R' U2 R U' R2' D' R U' R U' D2", "D U' L2' U' L2 U L' D' L U L' D L' U' L2 D'", "L U' L' D L2 U' L' U2' L U' L2' D'", "D U R' U R D' R2' U R U2 R' U R2 U'", "D' U R D R U' R' U2 R U' R' D' R' D R U' R' U'"],
    "DBL": ["U2 R D' R2' U R U2 R' U R2 D R' U'", "D U R' D R2 U' R' U2 R U' R2' D' R U2 D'", "D' U R' U R U R' U2' R2 D R' U R D' R' U' D", "D2 U R2 U' R' U2 R U' R2' D' R U' R' U' D'", "D' U R U2 R' D' r U2 r' D R2 U' R2' U' D", "L U' L' U' L U2 L2' D' L U' L' D L", "U' L2' U' L2 U L' D' L U L' D L' U' L2", "R D' r' U2 r D' R2' U R U2 R D2 R'", "U' R' D2 r U2 r' D R2 U' R' U2 R' D R U", "D U R2' D R2 U' R' U2 R U' R2' D' R U' R U' D'", "U R' U R D' R2' U R U2 R' U R2 U' D", "D2 U R D R U' R' U2 R U' R' D' R' D R U' R' U' D"],
};

var ltef = {
    "UB": ["L2 U: S', L2 + L F' L', S'", "R' U': S, R2 + U2: L E' L', U'", "L U: S', L2 + R' E R, U'", "U2, M' + R U' R' U, M'", "M, U2 + M U' M' U' M U' M' U'", "U': S, R2 + R' E' R, U'", "U: S', L2 + U2: L E L', U'", "R U': S, R2 + U2: L' E L, U'", "L' U: S', L2 + R E' R', U'"],
    "UL": ["L2 U: L2, S' + R' U' R U, M", "U, L' E2 L + U2: L E' L', U'", "E: U, L E' L' + R' E R, U'", "M U2 M, U' + R U' R' U, M'", "U l: U'/R' E R + M U' M' U' M U' M' U'", "U R U R' U' R' U' R' U R + R' E' R, U'", "U, L' E L2 E' L' + U2: L E L', U'", "U, L E2 L' + U2: L' E L, U'", "E': U, L' E L + R E' R', U'"],
    "LU": ["U' M: U/M' + R' U' R U, M", "S' U: L'/E' + U2: L E' L', U'", "r U: r' E r, U + R' E R, U'", "L' F': L2, E' + R U' R' U, M'", "D: L F' L', S + M U' M' U' M U' M' U'", "r: U', L E' L' + R' E' R, U'", "L F' L', S + U2: L E L', U'", "M': U', L' E L + U2: L' E L, U'", "U' l: U/M' + R E' R', U'"],
    "LF": ["U/R' E R + R' U' R U, M", "U2: R' E R, U + L F' L', S'", "E, R U' R' + U2: L E' L', U'", "U R' F2: R S R', F + R U' R' U, M'", "M/U' L' U + M U' M' U' M U' M' U'", "U' E': R/E' + R' E' R, U'", "U E: L/E' + U2: L E L', U'", "R': R' E R, U' + U2: L' E L, U'", "E', L U L' + R E' R', U'"],
    "LD": ["U'/L E L' + R' U' R U, M", "L E L', U + L F' L', S'", "U: L F2 L', S + U2: L E' L', U'", "S' U': R/E + R' E R, U'", "L F: E', L2 + R U' R' U, M'", "U: S', L B' L' + M U' M' U' M U' M' U'", "L' F' L, S + R' E' R, U'", "L E: L' U L, E + U2: L' E L, U'", "S' U': R'/E' + R E' R', U'"],
    "LB": ["U/R E' R' + R' U' R U, M", "U2: R E' R', U + L F' L', S'", "R: R E' R', U' + U2: L E' L', U'", "E, L' U L + R' E R, U'", "F: E', L2 + R U' R' U, M'", "M/U' L U + M U' M' U' M U' M' U'", "u': R'/E + R' E' R, U'", "u: L'/E + U2: L E L', U'", "E', R' U' R + U2: L' E L, U'"],
    "FR": ["R' U': R2, S + R' U' R U, M", "L' E2 L, U + L F' L', S'", "R' U': R/E + R' E R, U'", "U D': L/E' + R U' R' U, M'", "U D: L/E' + M U' M' U' M U' M' U'", "U R' U' R' U R U R U R' U2 + R' E' R, U'", "U: L/E' + U2: L E L', U'", "U: R'/S + U2: L' E L, U'", "R' U': R'/E' + R E' R', U'"],
    "FD": ["R' F': E, R U R' + R' U' R U, M", "L' U L U', M' + L F' L', S'", "U' R U, M' + U2: L E' L', U'", "U L' U', M' + R' E R, U'", "D': L' F' L, S + M U' M' U' M U' M' U'", "U R' F': R'/S + R' E' R, U'", "U' L F: L/S' + U2: L E L', U'", "U' R' U, M' + U2: L' E L, U'", "U L U', M' + R E' R', U'"],
    "FL": ["L U: L2, S' + R' U' R U, M", "E: L E' L', U + L F' L', S'", "R' U': R'/E + U2: L E' L', U'", "U' D: R'/E + R U' R' U, M'", "U' D': R'/E + M U' M' U' M U' M' U'", "U':  R'/E + R' E' R, U'", "U' L U L U' L' U' L' U' L U2 + U2: L E L', U'", "R U': R'/E + U2: L' E L, U'", "U': L/S' + R E' R', U'"],
    "RB": ["U'/L' E L + R' U' R U, M", "L' E L, U + L F' L', S'", "E', R U' R' + U2: L E' L', U'", "L': L' E L, U + R' E R, U'", "F': E, R2 + R U' R' U, M'", "M/U R' U' + M U' M' U' M U' M' U'", "u': R/E' + R' E' R, U'", "u: L/E' + U2: L E L', U'", "E, L U L' + R E' R', U'"],
    "RD": ["U/R' E' R + R' U' R U, M", "U2: R' E' R, U + L F' L', S'", "R' u': R/E' + U2: L E' L', U'", "U': R' F2 R, S' + R' E R, U'", "R' F': E, R2 + R U' R' U, M'", "U': S, R' B R + M U' M' U' M U' M' U'", "R F R', S' + U2: L E L', U'", "D': U' R' U, M' + U2: L' E L, U'", "R' E': R U' R', E' + R E' R', U'"],
    "RF": ["U'/L E' L' + R' U' R U, M", "L E' L', U + L F' L', S'", "E', L' U L + R' E R, U'", "R2 F': E, R2 + R U' R' U, M'", "M/U R U' + M U' M' U' M U' M' U'", "U' E': R'/E + R' E' R, U'", "U E: L'/E + U2: L E L', U'", "E, R' U' R + U2: L' E L, U'", "L: L E' L', U + R E' R', U'"],
    "BU": ["L U L' U', M + L F' L', S'", "U' R U, M + U2: L E' L', U'", "U L' U', M + R' E R, U'", "U: S, R' F' R + R U' R' U, M'", "U: S, l U l' + M U' M' U' M U' M' U'", "U D': S, R' F' R + R' E' R, U'", "U D: S, R' F' R + U2: L E L', U'", "U' R' U, M + U2: L' E L, U'", "U L U', M + R E' R', U'"],
    "BL": ["L' U: L2, S' + R' U' R U, M", "E': L' E L, U + L F' L', S'", "R' U': R/E' + U2: L E' L', U'", "U': L'/S' + R' E R, U'", "U' D: R/E' + R U' R' U, M'", "U' D': R/E' + M U' M' U' M U' M' U'", "U': R/E' + R' E' R, U'", "U' L' U' L' U L U L U L' + U2: L E L', U'", "R U': R/E' + U2: L' E L, U'"],
    "BD": ["U M': U'/M' + R' U' R U, M", "M U M' U M U M' U + L F' L', S'", "U': R, U' M U + U2: L E' L', U'", "U: L', U M U' + R' E R, U'", "D: L' F' L, S + R U' R' U, M'", "D' R' F': E, R2 + R' E' R, U'", "D L F: E', L2 + U2: L E L', U'", "U': R', U' M U + U2: L' E L, U'", "U: L, U M U' + R E' R', U'"],
    "BR": ["R U': R2, S + R' U' R U, M", "L E2 L', U + L F' L', S'", "U: R/S + U2: L E' L', U'", "R U': R/E + R' E R, U'", "U R': U/M' + R U' R' U, M'", "M2, U' R' U + M U' M' U' M U' M' U'", "U R U R U' R' U' R' U' R + R' E' R, U'", "U: L'/E + U2: L E L', U'", "R U': R'/E' + R E' R', U'"],
    "DF": ["M', U2 + R' U' R U, M", "R': F/R S R' + L F' L', S'", "U D': L'/E' + U2: L E' L', U'", "U' D: R/E + R' E R, U'", "u2 M' u2 M' + M U' M' U' M U' M' U'", "R': F/R S' R' + R' E' R, U'", "L: F'/L' S L + U2: L E L', U'", "U R': U'/M' + U2: L' E L, U'", "U' D: R'/E' + R E' R', U'"],
    "DR": ["U': R2, S + R' U' R U, M", "R' U' R U R U R U' R' U' + L F' L', S'", "U2 R U' R' U' R' U' R U R U' + U2: L E' L', U'", "U': R/E + R' E R, U'", "R' F': R S' R', F2 + R U' R' U, M'", "U' R D: R'/S' + M U' M' U' M U' M' U'", "U: L2, S + U2: L E L', U'", "R' U R U R U R' U' R' U' + U2: L' E L, U'", "U': R'/E' + R E' R', U'"],
    "DB": ["U2, M + R' U' R U, M", "U l: U/R' E R + L F' L', S'", "U D: L'/E' + U2: L E' L', U'", "U' D': R/E + R' E R, U'", "M' U2 M' U2 M2 + R U' R' U, M'", "U' R D: R/S' + R' E' R, U'", "U' D R D R' D' R' D' R' D R U + U2: L E L', U'", "U' R' U, M2 + U2: L' E L, U'", "U' D': R'/E' + R E' R', U'"],
    "DL": ["U: L2, S' + R' U' R U, M", "L U': L'/S' + L F' L', S'", "U: L'/E' + U2: L E' L', U'", "U2 L' U L U L U L' U' L' U + R' E R, U'", "L: F/L' S L + R U' R' U, M'", "U' R' D' R D R D R D' R' U D' + M U' M' U' M U' M' U'", "U': R2, S' + R' E' R, U'", "U: L/E + U2: L' E L, U'", "L U' L' U' L' U' L U L U + R E' R', U'"],
}

var t2c = {
    "UFL": ["U S R B' U' R2' U B U' R2 U R' S'", "R U' R2 D' r U2 r' D R2 U' R' U' R U' R' U", "U' R' U2 R U R2' D' R U' R' D R U2 R U2'", "U' D' R U R' U' D R D' R' U R2 D R2 D' R2 U' R' U D", "D R U' R' U D' R' U' R D' R' D U R2 D' R' D R'", "D R2' D R U2 R D' R' D U2 R' D' R U' R' U R D'", "R U' R' U R' U' R D' R' D U R2 D' R' D R'", "R U R' U M F R' F' r U' R U' R' U", "R2' D R U2 R D' R' D U2 R' D' R U' R' U R", "D' R U' R' U D R' U' R D' R' D U R2 D' R' D R'", "U2 R U' R' U' R U2' R' U' R' D' R U2 R' D R", "f U' R' U R' U' R2 U2 R' D' R U' R' D f'", "R' U' R U R' D' R U' D R D' R2' D R U R", "U' R U R' U' D R D' R' U R2 D R2 D' R2 U' R' U", "D R' D R U R U R2' D' r U2 M U D'", "D2' R' D R U R U R2' D' r U2 M U D2", "R' D R U R U R2' D' r U2 M U", "D' R' D R U R U R2' D' r U2 M U D", "R' D' R U2 R' D R U R U2' R' U R U R' U2'", "U' R U R' U r' F R F' M' U' R U' R'", "S R U' R2 U B' U' R2 U B R' S' U'", "R' U' R' D' R2 D R' U D' R' D R U' R' U R", "U' M' U2 r' D R2 U' R' U' R' D' R", "R' U' R D' R' U D R2 D' R' D R' U' D R U R' D'", "D' U' M' U2 r' D R2 U' R' U' R' D' R D", "U' R U2' R2' U' R2 U' R' F U' R' U' R U F' U", "R' U' R D' R' U D R2 D' R' D R' U' R U R'", "D2 U' M' U2 r' D R2 U' R' U' R' D' R D2", "U2' R' U2 R' D' R U R' D R2 U' R' U2 R U", "U' R U R' U R U R2' D' r U2 r' D R2 U R'", "D U' M' U2 r' D R2 U' R' U' R' D' R D'", "R' U' R D' R' U D R2 D' R' D R' U' D' R U R' D", "L' U' L' U' L U2 L' U' L2 D L' U L D' L' U' L", "D' R' U' R U R' D R U2 D' R D R' U2 R' D' R2 D", "D R' U' R U R' D R U2 D' R D R' U2 R' D' R2 D'", "R' U' R U R' D R U2 D' R D R' U2 R' D' R2"],
    "UBR": ["U' R D R' U2 R D' R' U' R' U2 R U' R' U' R U'", "U R U2 R D R' U' R D' R2 U R U2 R'", "M U2 r D' R2' U R U R D R' U", "U' R U R D R2 D' R D U' R D' R' U R U' R' U", "R' D R U2 R' D' R D R U R' U2 R U R' D' U'", "D' U' R U R D R2 D' R D U' R D' R' U R U' R' U D", "D' R' D R U2 R' D' R D R U R' U2 R U R' U'", "R' U2 R2 U' r' F R' F' M' U' R U'", "R U R' U R U R' U2 L R U' R' U L'", "D U' R U R D R2 D' R D U' R D' R' U R U' R' U D'", "D M U2 r D' R2' U R U R D R' U D'", "U' D' R D R D' R' U D' R U' R' U D R2' D R2", "U' R D R D' R' U D' R U' R' U D R2' D R2 D'", "U' R D' R' D' U' R2 U' R2 D M U2 r D R'", "R' U' R2 D' R2 D R2 U R' D' R D U' R' U R", "L U' R U R' L' U2 R U' R' U' R U' R'", "U R' U R U R' U2' R U R D R' U2 R D' R' U", "D U' R U R' U' R D R' U D' R' D R2 D' R' U' R' U D'", "R' D R U R' D' R2 U' R' U2 R L U' R' U L' U", "U' R U R' U' R D R' U D' R' D R2 D' R' U' R' U", "R' U' R U D' R' D R U' R2 D' R2 D R2 U R", "D' U' R U R' U' R D R' U D' R' D R2 D' R' U' R' U D", "D R2' D' R2 U' D' R U R' U' D R D R' D' R' U", "R U2 R' U' R2 D R' U R D' R' U2 R' U'", "R2' D' R2 U' D' R U R' U' D R D R' D' R' D U", "U R' U M F R F' r U R2 U2 R", "U' R D' R' U' R' U' R2 D r' U2 M'", "D U' R D' R' U' R' U' R2 D r' U2 M' D'", "U D R U' R' U2 R U' R' D' R' D R U2 R' D' R", "U R U' R' U2 R U' R' D' R' D R U2 R' D' R D"],
    "UBL": ["U f' L B L2 B2' L F L' B L S", "D R' D' R U R' D R2 U' R' U2 R U' R' U2 D'", "L' U L U2 L2' U l F' L F M' U", "R' D' R U R' D R2 U' R' U2 R U' R' U2", "U R F' R' U D R U' R' U' R U2' R' U D' R F R'", "D' R' D' R U R' D R2 U' R' U2 R U' R' U2 D", "D2 R' D' R U R' D R2 U' R' U2 R U' R' U2 D2", "R U F' U' R' U2 R U' R' U' R U' F U' R' U", "U D' R' U' R U2 R' U' R2 D R' U R D' R' U D", "U R' U' R U2 R' U' R2 D R' U R D' R' U", "U' L' U' L U2' L' U' L2 D L' U L D' L' U'", "U D R' U' R U2 R' U' R2 D R' U R D' R' U D'", "D' U' R D R' U' R D' R2' U R U2 R' U R U' D", "U' M F' L' F l' U' L2 U2 L' U' L", "U L D L' U' L D' L2' U L U2' L' U L U", "R F' R' D U' R U2' R' U R U R' D' U' R F R' U'", "D U' R D R' U' R D' R2' U R U2 R' U R U' D'", "U' R U F' U R' U R U R' U2 R U F U' R'", "U' L U' L' U2 L2 U' l' B L' B' M", "U' R D R' U' R D' R2' U R U2 R' U R U'", "D2 U2 R U R' U2 R U R2' D' R U' R' D R D2", "D' U2 R U R' U2 R U R2' D' R U' R' D R D", "D U2 R U R' U2 R U R2' D' R U' R' D R D'", "U2 R U R' U2 R U R2' D' R U' R' D R"],
    "DFR": ["U D' R' D R U2 R D' R2 D R U R' U' D' R U D R'", "R' U' R D R D' R2 D R2 U R' D' R U' R' U R", "L' U R U2 R' U L U' D R U' R' U R U2 R' D'", "D' L' U R U2 R' U L U' D R U' R' U R U2 R'", "U2 R U R' U' R' D' R U' D R2' U R2 U' D' R' D R", "D' R' U' R D R D' R2 D R2 U R' D' R U' R' U R D", "U R D' R' U R U R' U2 R U D R2 D' R U' R' D R", "U R' U2 R D R' U' R D' R2 U R U2 R' U R2 U'", "U D R' U2 R D R' U' R D' R2 U R U2 R' U R2 U' D'", "R' D' R D U R2' U' R2 D' U R' D R U R U' R' U2", "U D R2' U' R U2 R' U' R2 D R' U R D' R' U2 R U' D'", "R' U' R U R' D R U' R2 D' R2 D R' D' R' U R", "U R2' U' R U2 R' U' R2 D R' U R D' R' U2 R U'", "R' D' R U R' D R2 D' U' R' U2 R U' R' U' R D R' U'", "R U' F' R U R' U' R' F U D R2 D' R' D R' D' R'", "R D' U' R' D U R U' R' D' R2 D R' U2 R' D' R D U'", "D' R' U' R U R' D R U' R2 D' R2 D R' D' R' U R D", "R' F R2 U' D R' U R2 U' R2 D' R U R F' R"],
    "DFL": ["L U f' L B L2 B2' L F L' B L S L'", "R U' R U R' U R' D R U' R2 D' R2 D U' R' D' U R'", "L' U' M' U2 r' D R2 U' R' U' R' D' R L", "D R D' U' R' D U R U' R' D' R2 D R' U2 R' D' R U'", "U D2 R2 U' R U2 R' U' R2 D R' U R D' R' U2 R U' D2", "D R' D' R U R' D R2 D' U' R' U2 R U' R' U' R D R' U' D'", "U D2 R' U2 R D R' U' R D' R2 U R U2 R' U R2 U' D2", "U R' D R U2 R D' R2 D R U R' U' D' R U D R' D'", "U R' D' M S' D' S r U' R' D2 R' D' R2", "U D R D' R' U R U R' U2 R U D R2 D' R U' R' D R D'", "D R' U' R D R D' R2 D R2 U R' D' R U' R' U R D'", "R U' D R U D' R2' D R2 U R' D' R U' R U' R' U R'"],
    "DBL/DBR": ["U D' R' U2 R D R' U' R D' R2 U R U2 R' U R2 U' D", "B U' R U R D R2 D' B' R D R U' R' U R D' R'", "f D' R2 D2 R' U' R D' R' D' U R' D R' f'", "f' D U' L D' L2' U L f L' B L B' R B R'", "U D' R2 U' R U2 R' U' R2 D R' U R D' R' U2 R U' D", "R D R' U' R U R' D' R' B D R2 D' R' U' R' U B'"],
}

var uf_ur_2c = {
    "UFR": ["f U R U R2' U' D' R U R' D R2 U2' f'", "R U R' F' R U R' U' R' F R2 U' R' U'", "U L' U' L F L' U' L U L F' L2' U L", "U R' U' R U R' F' R U R' U' R' F R2 U2", "U2' R' U R U2' R' r' F R F' r", "f U2' R U R2' U' D' R U R' D R2 U f'", "R U D' R' F' R U R' U' R' F R2 U' R' U' R D R'", "r B' U2' R2' F R F' R U2' r' U r B r'", "U R U' R U R' F' R U R' U' R' F R2 U' R2' U'", "L' U L' U' L F L' U' L U L F' L2' U L2", "U R' U R U' x' U L' U L U2' R U' R' U x", "U D' R U' R U R' F' R U R' U' R' F R2 U' R2' U' D", "U2' R' F R2 U' R' U' R U R' F' R U R' U", "S U' R U R2' F R f' U R U R' U'", "r' U' F R' F' R2 U' R' U2 r U'", "U D2 R U' R U R' F' R U R' U' R' F R2 U' R2' U' D2", "f R D R' U R U' D' R2' U R U' R f'", "U' r2' D' r2 U r2' U' r2 U r2' D' r2 D", "D U R2' U' R2 U R2' D' R2 U R2' U' R2 U2", "U R2' U' R2 U R2' D' R2 U R2' U' R2 U2 D", "D U' r2' D' r2 U r2' U' r2 U r2' D' r2"],
    "UFL": ["U2 R U' R' U' R U R' U R' D' R U' R' D R2 U R' U", "U' R' U R U' R' f' U' R U2 R' U' R U' R' f R U", "U L' F' U' L U2 L F' L' f L' U' L S' L' F L", "D R U' R2' D' R2 U D R' D' R U' R' U R'", "R U' R' D2 R' D' R2 D R' U D' R' D'", "R U' R2' D' R2 U D R' D' R U' R' U R' D", "D' R U' R' D2 R' D' R2 D R' U D' R'", "D R U' R' U R' D' R U' R U D R' D' R U' R' U R'", "R D' R' D' R U' R' D2 R' D' R2 D R' U R'", "R U' D' R U R' D R2' U' R U R", "U2 F R U R2' F R F' R U' R' F' U'", "R U R D R' U' R D' R' U2 R' U' R U' R' U'", "U' R' D R U R' U' D R D' R D R' U R' D' R D' R", "D R U' R' D2 R' D' R2 D R' U D' R' D2", "D R' U' D' R2 U R' D R U' D' R2 D R U R D'", "R' U' D' R2 U R' D R U' D' R2' D R U R", "D' R' U' D' R2 U R' D R U' D' R2 D R U R D", "U' R U R' D2 R' D' R2 D R' U D' R' D' R U2 R' U"],
    "UBR": ["R' U2 R' D' R U' R' D R U R U' R' U' R U'", "R U2' R' U' R' F R2 U' R' U' R U R' F' R U' R'", "R' D R2 U R' F' R U R' U' R' F R2 U' R' U' R' D' R", "l U2 L F' L' U' F l' U' l2 F' l2' ", "R U' R' D R D' R' D R' D' R2 D R' U R' D'", "U' R D' R D' R' U R' D R D' R U' D R' U R D R'", "D' R U' R' D R D' R' D R' D' R2 D R' U R'", "U R U' R' U2 R' D' R U' R' D R U R U' R' U2", "U R U' L U L' U R' U' l U2 R U2' l' R'", "U' R' U D' R' D R2 D' R' D2 R' U' R U D'", "U D' R U' R' U2 R' D' R U' R' D R U R U' R' U2 D", "R' U2 R D' R' U D' R' D R2 D' R' D2 R' U R", "U' D R U R U' R' U D R2 U' R' U R2 U' D' R' U D'", "U' R U D R2' U' R D' R' U D R2 D' R' U' R' U", "D R' U2 R D' R' U D' R' D R2 D' R' D2 R' U R D'"],
    "UBL": ["r U' r2 U' F U r2 U2 F U F' U2 r'", "x' U' r U r' U' F' U F U2' R U R' U2' x", "R' U' F R U R' D R U' D' R D R2' D' F' R U R", "F R U2' R' U' R U' R' F' R' D R U' R' D' R", "M' U' r' U r U r' U R U2 f R f'", "U M' U R U' r' U' R U B U' B' U2' R' U", "B' R' U2 R' D' R U' R' D R U R U' R' U' R U' B", "L U' R' U L' U' R U2 R' U' R U2 R' U' R U2", "U' R U2' R' L' U R U2' R' U L U' R U' R' U2", "R U R' U' R2' f' U' f R U f R' f' R2 U'", "R U f' U' f U D R' U' R D' R U' R' f R' f'", "L U L' F' U' L U2 L F' L' f L' U' L S' L' F"],
    "DFR": ["R U' D R U' R2' D R' D' R2 U D R' U D2 R'", "R' D' R U' R' D R' D' R2 U R U' D R' U D' R' D", "R' U' D R D' R D R' U R' D' R D' R U' R' D R U", "U D R2' D' R U R U R' U' R U' R D R' U R' U' R D'", "U2 R D' R' U2 R U' D' R' D R' D' R2 D R' U D R'", "R U' D R2' U' R D' R' U D R2 D' R' U R'", "R' U' D R' D' R2 D R' U D' R' D' R U' R' U D R", "R U' R U' R2' D R' D' R2 U D R' U D' R'", "R U' D' R U R2' U' R D R' U R' U' R U R"],
    "DFL": ["U D' R2' D' R U R U R' U' R U' R D R' U R' U' R D", "D' R U' R' D2 R' D' R D R U R' D' R U' D R' U D' R'", "D2 R U' D R2' U' R D' R' U D R2 D' R' U R' D2", "D R' D' R U' R' D R' D' R2 U R U' D R' U D' R'", "D R U' D' R U R2' U' R D R' U R' U' R U R D'", "D R' U' D R' D' R2 D R' U D' R' D' R U' R' U D R D'"],
    "DBR": ["D' R U' D R2' U' R D' R' U D R2 D' R' U R' D", "U R2' D' R U R U R' U' R U' R D R' U R' U' R", "D' R U' R U' R2' D R' D' R2 U D R' U D' R' D"],
};

var uf_ur_2e2e = {
    "UB": ["U' M2' U2 M U M2' U M2' U M", "f: U R U' R' + U R': F' U' F U", "L U': S, U r U' r'", "U': S, U r U' r'", "L' U': S, U r U' r'", "r U' r' S' R U R' S U' M' U M", "D' U': S, U r U' r'", "M' U' r' F R S r' F' r S' U", "U' f R' f' R2 U' F' U F R2' U2'", "U: U R B' R', S'", "U2 R' F R2 U R' U' R' F' R U2 R U' R' U", "U' M' S R B R' S' r B' r' U M", "D U': S, U r U' r'", "U: S' R' U R S r' U' R U M' U'", "M U2 M U M' U2 M' U M' U2 M", "U: U, R' F R S' R' F' R", "M2 U' M' U2 M' U M' U2 M", "M U2 M' U' M S U' S' M'"],
    "UL": ["U2, R' E R + U', R' E R", "U' r' U r, S", "U2, R E' R' + U', R E' R'", "U: M' U R U' r' S' R U R' S U'", "D': U' r' U r, S", "r' U2 F' R' F R U2' F r U'", "U F R: S', R' F' R U", "U2: U' R' F R, S'", "U R2' F R: S', R' F' R U", "L U r' F' U2' R' F' R F U2' x", "U r' F R S R' F' R S' U' M'", "f2 R D R' D' f2 R' U' R U", "D: R' U R' S R2 S R' U' R S2", "R' U R' S R2 S R' U' R S2", "D': R' U R' S R2 S R' U' R S2", "R' U R' S R2 S R' U' R' S R2 S"],
    "FR": ["R' E R, U' + U': R U R', E", "S' R' S R2 E' R' E + U', R E' R'", "U', R E' R' + R: U', R E' R'", "F' R' F R U' F' R U R' U' F U", "R' U R u': U2 R2 U2 R2 U2 R2", "E': U', R' E R + E', R U' R'", "R E R', U' + R U': E, R' U R", "L U: M' U R U' r' S' R U R' S U'", "M2' U R U' M' U r' U' M' U M' U'", "U: R'/S + U: U, R' S2 R", "R U r': U/M2'", "U R U' F' U F R' U' F R F' R'", "U R' U': U M S' U S U2' M'", "U: L/E' + U: U, L' E2' L"],
    "FL": ["U', r' E r + U E: L'/E'", "x' F' U R S R' U' F R S' l'", "r': F', R U M' U' R'", "U' R': R' E R, U + U', R' E R", "E': R/E' + U', R' E R", "L'/S' + U', L' S2 L", "U M2' U' L' U M' U' l U M' U' M'", "R' E' R u' R' E' R E' R' E R U R' E R", "L: U' S M' U' M U2 S'", "R' U: R/S + R'/E", "L U: U' M S U' S' U2 M'", "r' F D F' D' r U F' r' D r U' "],
    "DF": ["r' B R S R' B' R D S' D' M'", "L U': M, U r U' r' U'", "U' R' U, M' + R U' R' U, M'", "R' F': E, R2 + R' E' R, U'", "L': U' S M' U' M U2 S'", "M, U M U'", "U R: U S' M' U M U2' S", "U: U S' M' U M U2' S", "R U R': U/M2", "U' S M' U' M U2 S'"],
    "DB": ["U' M' D' S D R F' R' S' R F r' U", "L U r' F R S R' F' R S' U' l'", "U r' U' S' r U' r' S r U R' U R U'", "R E R', U' + R' B R, S", "L': M S U' S' U2 M' U'", "U R: M S' U S U2' M' U", "U M S' U S U2' M'", "M S U' S' U2 M' U'"],
    "DR": ["U' S U, S", "L', S' + U' L', S", "u': R/E' + U2': R' S' R, U'", "R' U R S R2' S' R3 E' R2' u' R", "F2 R D R' D' F2 R' U' R U", "S' R' F: R'/S + S', R2"],
    "DL": ["u: L'/E + r E' r', U'", "U: R, S + U: U R, S'", "f' r' E r f r U' r' S' r U r'", "f R' S R f' r U' r' S' r U r'"],
    "LB/RB": ["U', R E' R' + u: R'/S", "U', R E' R' + R' U' R, E'"],
};

var _3bld_parity = {
    "UFR": ["F R U' R' U' R U R' F' R U R' U' R' F R F'", "R U R' F' R U R' U' R' F R2 U' R' U'", "U' R U R' F' R U R' U' R' F R2 U' R'", "U R' U' R U R' F' R U R' U' R' F R2 U2", "U' D' R U R' D R2 U' R U R2'", "U' r' D r U' r' D' r U' r' D r U' r' D' r U'", "R D' U R' F' R U R' U' R' F R2 U' R' U' R D R'", "r B' U2' R2' F R F' R U2' r' U r B r'", "U R U' R U R' F' R U R' U' R' F R2 U' R2 U'", "D U2 R' F R2 U' R' U' R U R' F' R U R' U D'", "U R' U R U' x' U L' U L U2 R U' R' U", "U' R2' F R F' R U2 r' U r U'", "U2' R' F R2 U' R' U' R U R' F' R U R' U", "S U' R U R2' F R f' U R U R' U'", "U' R' U' R U R' F' R U R' U' R' F R2", "D' U' R2' F R F' R U2 r' U r U' D", "f R D R' U R U' D' R2' U R U' R f'", "U' r2' D' r2 U r2' U' r2 U r2' D' r2 D", "D U R2' U' R2 U R2' D' R2 U R2' U' R2 U2", "U R2' U' R2 U R2' D' R2 U R2' U' R2 U2 D", "D U' r2' D' r2 U r2' U' r2 U r2' D' r2"],
    "UFL": ["U2 R U R' F' R U R' U' R' F R2 U' R' U", "U F R U' R' U' R U R' F' R U R' U' R' F R F' U'", "U R' F R U' R' U' R U R' F' R U R' U' R' F R F' R U'", "D R U' R U R' F' R U R' U' R' F R2 U' R2' D'", "U' R U D' R' F' R U R' U' R' F R2 U' R' U' R D R' U", "R U' R U R' F' R U R' U' R' F R2 U' R2'", "U D R U' R' U' R U R' F' R U R' U' R' F R U' D'", "r U2 R2 F R F' R U2 r' U", "D' R U' R U R' F' R U R' U' R' F R2 U' R2 D", "U R U' R' U' R U R' F' R U R' U' R' F R U'", "R' U' R U R' F' R U R' U' R' F R2 U'", "U R' U R U2' L' R' U R U' L U", "U D' R2 U' R' U' R U R' F' R U R' U' R' F U' D", "U D' R U' R' U' R U R' F' R U R' U' R' F R U' D", "D2 R2 U' R2 U R2 D' R2 U R2 U' R2 U' D'", "D R2 U' R2 U R2 D' R2 U R2 U' R2 U'", "R2 U' R2 U R2 D' R2 U R2 U' R2 U' D", "D' R2 U' R U R' F' R U R' U' R' F R2 U' R D"],
    "UBR": ["U R U R' F' R U R' U' R' F R2 U' R' U2", "U2 R U' R' U2 L R U' R' U L'", "L' U L U L' U' L F L' U' L U L F' L'", "U' D2 R' F R2 U' R' U' R U R' F' R U R' D2", "U2 R U' R U R' F' R U R' U' R' F R2 U' R2 U2", "U' D R2 U' R' U' R U R' F' R U R' U' R' F U D'", "U' R2 U' R' U' R U R' F' R U R' U' R' F U", "U' R' F R2 U' R' U' R U R' F' R U R'", "R' F R U' R' U' R U R' F' R U R' U' R' F R F' R", "U' D' R2 U' R' U' R U R' F' R U R' U' R' F U D", "U' D' R' F R2 U' R' U' R U R' F' R U R' D", "U' D R2 U R2' U' R2 D R2' U' R2 U R2' U2 D2", "U' R2 U R2' U' R2 D R2' U' R2 U R2' U2 D'", "U' D' R2 U R2' U' R2 D R2' U' R2 U R2' U2", "U' D2 R2 U R2' U' R2 D R2' U' R2 U R2' U2 D"],
    "UBL": ["U' D R U' R U R' F' R U R' U' R' F R2 U' R2' U D'", "D2 R' F R2 U' R' U' R U R' F' R U R' U' D2", "D R2 U' R' U' R U R' F' R U R' U' R' F D'", "D R' F R2 U' R' U' R U R' F' R U R' U' D'", "R2 U' R' U' R U R' F' R U R' U' R' F", "R' F R2 U' R' U' R U R' F' R U R' U'", "D' R2 U' R' U' R U R' F' R U R' U' R' F D", "D' R' F R2 U' R' U' R U R' F' R U R' U' D", "F' R U' R' U' R U R' F' R U R' U' R' F R F", "R2 U R2' U' R2 D R2' U' R2 U R2' U D'", "D' R2 U R2' U' R2 D R2' U' R2 U R2' U", "D2 R2 U R2' U' R2 D R2' U' R2 U R2' U D"],
    "DFR": ["R' U' D R D' R D R' U R' D' R D' R U' R' D R U", "R D' R' F' R U R' U' R' F R2 U' R' U' R U D R'", "U' D R2 U R2' D' R' U' R U R' D R D' R", "F' R' U R2 U' R' U R' U' F D R D' R'", "U D R U' R' D R U R' U' R' D R D R' D2 R D'", "R' D' R F R' D' R D R F' R2' D R D", "R D R2' D' R U' R' U D R2 U' R' U D' R'", "D' R' U' D R D' R D R' U R' D' R D' R U' R' D R U D", "R D2 R' D R D R' U' R' U R D R' U' R U"],
    "DFL": ["U' D2 R2 U R2' D' R' U' R U R' D R D' R D'", "R D R' D' R F R' D' R D R F' R2' D", "D R' U' D R D' R D R' U R' D' R D' R U' R' D R U D'", "R2 D' R2 D' R2 D R2 U' R2 D R2 D' R2 U R2", "D R D2 R' D R D R' U' R' U R D R' U' R U D'", "D R D R2' D' R U' R' U D R2 U' R' U D' R' D'"],
    "DBL/DBR": ["U R2' D' R U R U R' U' R U' R D R' U R' U' R", "U D' R2 U' R2 D R U R' U' R D' R' D R' ", "R' D' R2 D R' U R U' D' R2' U R U' D R"],
};

var full_parity = {
    "UBL": ["U2' R F U' R' U R U F' R2' F' R U R U' R' F", "f U R U R2' U' D' R U R' D R2 U2' f'", "L' b' L U L' U L U2' L' U b L U L' U' L", "F U2 D R' D' R2 U D R' D' R U' R2' U2' F'", "F r U' r' U r2 U2' R' F R U2' r F' r", "L' D F' U' R' F' R2 U' R' U R' F R U D' L", "z U' R U R' F R' F' R2 U' R' F' U' F U z'", "U' F' R' F R U R' F U' F U F2 R U' F U", "F U' F' U' R' F R U F U2' R U R' U2 F'", "r' U' F U' R' F' R U' R U R2' F R U2' r", "S U R U' R2' F R f' R U' B U2' B' R'", "F U2' F' U2' r2 U' F' U r2' U' F U F'", "F U R U R2' U' D' R U R' D R2 U2' F'", "r' F r U' F U' R U' R' U2 r U' r' F'", "R' U R2 f' U' f R' U F' U2' F R U'", "R' u2 R' F' R2 U' R' F' U' F R U R' F u2' R", "r' U R U' R' U R' F R U F' U' R' F' R U' r", "U' R U' R' D R2 U' R U R2' U' D' R U2 R' U", "r' U' r U r2' F2 R U R' F2 r F' U r", "U R U' R2' F R f' R U' B U2' B' R' S", "F U' R U2' r' U r U2' R2' F R F' U F'", "F S' U R U R2' U' D' R U R' D R2 U2' F' S"],
    "UBR": ["R' F R f' R' F R2 U R' U' R' F' R2 U R' S", "R U R' F' R U R' U' R' F R2 U' R' U'", "U' R' U2 R' D' R U' R' D R U R U' R' U' R", "S R U R' F' R U R' U' R' F R2 U' R' U' S'", "u' R' U2 R' D' R U' R' U' D R' U R2 E'", "U D F2 R U' R' F R U R' F U' F D'", "R u R' F' R U R' U' R' F R2 U' R' U' R E R'", "U' R' U2 R' D' R U' R' U' D R' U R2", "U F2 R U' R' F R U R' F U' F", "F R U R' U R U R' U2 R' F' r U R U' r'", "M r' F R F' R U2' r' U r U2' M r'", "R U' R' U D R' U' R f' R' U' R f U D'", "F R U R2' U' D' R U R' D R2 U' F'", "R U' R' U S' U F' U' F U R U' R' U' S", "R' F' U2 R' F R U' R' F' R U' F U' R", "F R' F R u' R' U R' F' R2 D R' U' R' y", "U2 l U' F U' F' U2' R' F R U' l' U", "R' U2' R' F R2 U' R' U' R U R' F' R U R' U R", "D R' U' R U' R2' D R' D' R2 U D R' U D' R D'", "R' U' R U' R2' D R' D' R2 U D R' U D' R", "D' R' U' R U' R2' D R' D' R2 U D R' U D' R D", "r' U F U' r f R' U R U R' U' f'"],
    "UFL": ["U' R U R' U' R' F R2 U' R' U' R U R' F' U", "U L' U' L F L' U' L U L F' L2' U L", "U' R U R' F' R U R' U' R' F R2 U' R'", "M' U' R' F R F' U R U r' U2 R U R' U", "l' U R U2' r' R' F R F' r U2'", "S U' R U R' F' R U R' U' R' F R2 U' R' S'", "U' R' F R F' R U' R u R u' R' U R' U", "U' R' U' R D' R' U D R2 D' R' D R' U", "U' R' F R F' r U2' R' U R U2' r' U", "r' F U' R' F' R U' R U R2' F R U r", "S' U' R U R' F' R U R' U' R' F R2 U' R' S", "U r' F U R U R' F' U2' F U F2 r", "U' D' R' F R F' r U2' R' U R U2 r' U D", "r U' R U R' L' U2 R U R' U2 x'", "R U' R' F' U F R U R2' F R F'", "z R' F' R2 U' R' F' U' F R U R' F z'", "U' R' F R F' R U2' r' U r U2' R' U", "U' R U R' D R U' D' R2' D R D' R U", "r' F r' F2 R U' R' F2 r2 U'", "D' r' F r' F2 R U' R' F2 r2 U' D", "U2' R' U R' F2 r F' r' F2 R2 U", "D r' F r' F2 R U' R' F2 r2 U' D'"],
    "LUB": ["M' U R' F2 r F' r' F2 R2 U' r'", "U R' U' R U R' F' R U R' U' R' F R2 U2'", "R2 U2' R2' F R F' R U' R' F' U F R U' R2'", "M' U r' F2 R F' R' F2 R r U' r'", "U' f U' R U R2' F R f' U R U R' U' F' U", "r D' R' U R' F2 r F' r' F2 R2 U' D r'", "U2 R U2' F' U' F U' R2 u R' u' R U2'", "R U R2' F R U R U' R' F' R U2' R' U2", "U R' M' F R' F' R2 U' r' F' U' F R", "r U R' U F' U' R' F R U F U2' M", "M U R' U' R l U2 r' U' r U2 R' M' x", "U R' U' R U' F R' F' U' r U R U' r' U", "F U2 R U' D' R2' U R U' R2 D R' U' F'", "U r U' R' U' R U r' F R' F' R U' R' F R F'", "U R B U' B' R' F R' F' R2 U' R'", "L R U' R' U2 L R U' R' U L' U2 L'", "U' R U2' R2' F R F' R U2' r' U M' U", "U' F R U R' D R2 U' R U R2' U' D' F' U", "U' F U R' F' R U' F' U M' U R U' r'", "U2' R U D R' U' R D' R2 U R' U' R U2'", "r U2' r' F r' F2 R U' R' F2 r2 U r'", "L U D L' U' L D' L2 U L' U' L"],
    "LUF": ["r U' r U2' R' F R U2' r2' F", "R' U' R2 U R' D R U' D' R2' D R U D' R", "R U' R' U2 L R U' R' U L' U2", "L F' U' R' F' R2 U' R' U R' F R U L'", "R' F D F D' F2 R D R' F R D'", "U' D R U R2' F R U F U' R' F' R D'", "F' U' F U' R2 u R' u' R2 U2'", "U' D R' U' R D' R2 U R' U' R2 U2'", "U' R U R2' F R U F U' R' F' R", "U F' r U' r' F R' F' R F R U2' R' U", "F D R' D' R2 U D R' D' R U' R2' F'", "U2' r2 U' F' U r2' U' F U' F'", "F U' R U R2' U' D' R U R' D R2 F'", "r U' R U2' r' F r U2' r' R' F", "U2' R U R' S R' F R f' U R U R'", "U D L' U' L D' L2 U L' U' L2'", "F R U' R' U R' F2 r F' r' F2 R F'", "U' D' R U R' D R2 U' R U R2'", "M' r U' r U2' R' F R U2' r2' F M", "D F2 R F' R U2' r' U r U2' R2' F' D'", "F2 R F' R U2' r' U r U2' R2' F'", "D' F2 R F' R U2' r' U r U2' R2' F' D"],
    "LDF": ["F' r F2' R' D R F2' r2' D r", "U D R U' R U R' F' R U R' U' R' F R2 U' R2' U' D'", "L' U D L' U' L D' L2 U L' U' L'", "U' R' F R U R' F U' F U F2 R", "F' U' R' F' R2 U' R' U R' F R U", "U r' D r U r' D' r U r' D r U r' D' r U", "L' U' D R U R2' F R U F U' R' F' R D' L", "U' E' R' F' R U' R U R2' F R U F E", "U' R' F R U F U2' R U R' U F'", "r' F2 r U' r' F2 r R U' r' F M'", "R' F R U R' F U' F U F2 D R U' R' D' R", "F U' F' U2' r2 U' F' U r2' U'", "F U2 R U R2' U' D' R U R' D R2 U F'", "x r U2' R2' F R F' R U2' r' U x'", "R' U' R' F' R2 U' R' U2 R U2' R' F R U", "E F' U' R' F' R2 U' R' U R' F R u ", "F U' F' U2' r' F R U' R' F' r U'", "U' D R D R2' U' D' R D R' U R2 U D2", "M' F' r F2' R' D R F2' r2' D R", "R' D R2 U' R' U2 R' D' R U' R' U' D R' U D' R", "F R U2' r' U r U2' R2' F R F2'", "S U' R' F R U R' F U' F U F2 R S'"],
    "LDB": ["r2' B' r2 D2 R' B' R D2 r' D r", "R U D' R' F' R U R' U' R' F R2 U' R' U' R D R'", "U' l U2 r U' r' U' F R' F' R2 U' R' l' U", "r' U' r' B' r2 D2 R' B' R D2 r' U D r", "L' U' R' F R U R' F U' F U F2 RL", "D R' F' R2 U' R' U R' u' R' u R F D'", "LM' U L' U2 R U' R' U2 L R U' r' L'", "R U' R' U D' R' D R2 D' R' D2 R' U' R U D' R'", "U' L U2 r U' r' U' F R' F' R2 U' R' L' U", "L2 U D L' U' L D' L2 U L' U'", "l U R' U' R l U2 r' U' r U2 R' l' x", "D2 R U' R' U D R' U' f' U' f U R D", "r U D' R' U R2 D' R D R2 U' D' R U' D2 r'", "r' D' r D F' R2 U' R' U R' F D'", "U' D' F R' F' U' F R F' U2 R' U' R D", "U r' D r U' r' D R2 U' B U R2' D2 r", "D' F R' U R' U' R2 U D R' U' R D' R' F' D", "U' D2 R U' R2' D R' D' R2 U D R' U D", "R' r' B' r2 D2 R' B' R D2 r' D R", "D r' F2 r U' r U2' R' F R U2' r2' F' r D'", "L2 F2' L' F L' U2 l U' l' U2 L2 F L2'", "D2 R U' R' U2 R' D' R U' R' U' D R' U R D2"],
    "FUL": ["R U2' R' U R U' R' F' U' F R U R' F R' F' R U'", "r B' U2' R2' F R F' R U2' r' U r B r'", "R' U R2 U R2' U' R2 D R2' U' R2 U R2' D' R", "U F2 r2 U2' R' F R U2' r2' F r U' r' F2 U'", "l' F R U' R' U' R U R' F' R U R' U' R' F R F' l", "S R' U R2 U R2' U' R2 D R2' U' R2 U R2' D' R S'", "E' R' D R2 U' R2' D' R2 U R' D R' D' R U' R' U E", "R2' U' R U R' D R D' R U' D R2' U R2 D' R", "r R U' R2' F R F' R U' B U2' B' R' U r'", "L2' b' L U L' U L U2' L' U b L U L' U' L2", "R' U R U R' F R' F' R2 U' R' F' U' F U' R", "R' U r U r' F2 R F' r U r' R' F2 U' R", "R2' F R D R2' U' R U R2' U' D' R U R2' F' R2", "r' U r2 U' r2' D r2 D' r2' D r2 U' r2' D' r", "R2 U' R2' F R F' R U' B U2' B' R' U R'", "L D' L2' U L2 D L2' U' L D' L D L' U L U'", "B R' D R2 U' R2' D' R2 U R' D R' D' R U' R' U B'", "R' D R2 U' R2' D' R2 U R' D R' D' R U' R' U", "U' D R D' R' U R' D R2 U' R U D' R' D R2 D'", "U' R D' R' U R' D R2 U' R U D' R' D R2", "U' D' R D' R' U R' D R2 U' R U D' R' D R2 D", "F r U' r' F' D r2 U r' U' r' F r F' U2 r' D'"],
    "FDR": ["D' F' r F2' R' D R F2' r2' D r D", "U R U' R U R' F' R U R' U' R' F R2 U' R2' U'", "F R' F' R2 U' R' U R B U' B' R'", "U' D' R' F R U R' F U' F U F2 R D", "u' R' u R F R' F' R2 U' R' U R'", "f R' F' R2 U' R' U R B U' B' R' S'", "U2' R B R2' D' R U F R' F' D R U", "U' R' u R F R' F' R2 U' R' U R' E", "U' R' F R U F U' R' F' R U' R U R' U", "r' F' R2 U' R' U R' F R U F' U' M'", "F' r' F r F U' R U R' r' F R F' M'", "R F R' F' U2 R' U2' F' r U' r' F2", "R U' R U R2' E F R F' R' U' R u", "u' R U' R' U D R2 U' R' U R2 y", "F' r' F r F U' R U R2' F R F'", "L F R' F' R2 U' R' U R B U' B' R' L'", "r U' r' U r' F' r2 U2' R' F' R U' r'", "U' R D R2' U' D' R D R' U R2 U D'", "l U L F L2' U2 l U l' U2 L F' U' l'", "R U r U' r' U' F R' F' R r U' R' U r'", "U' R' M' F R U F U' R' F' R U' R U r' U", "D' F R U2' r' U r U2' R2' F R F2' D"],
    "FDL": ["U' D F' R U R' U' R' F R2 U' R' U' R U R' U D'", "U2 D R' F R2 U' R' U' R U R' F' R U R' U D'", "D R U' R' U2 R' D' R U' R' D R U R U' R' U' D'", "R' F2 r U' r' U' F R' F' R2 U' R' U2' F2 R", "l' U' R' F R F' U R U r' U2 R U R' U L", "z' u' U' R U R2' U' D' R U R' D R2 u z", "r' U' D' r F r' U r2 U' r B r' x'", "D R2 U R' F' R U R' U' R' F R2 U' R' U' R' D'", "R' F' R2 U' R' U R' u' R' u R F", "M F' r U2' R' U R U2' R' r' F r", "r' U' D R D R' U R2 D' R D R2 D2 r", "D R U' R' U D R' U' f' U' f U R D2", "r' U D R' D' R U' R2 D R' D' R' M'", "F R U R' F U' F U F2 R U' R'", "D F' U2 R' F R U' R' F' R U' F U' D'", "r' F D F' D R2 U' B U R2' D2 r", "L' U' R' F R F' R U2' r' U r U2' R' U L", "U' D R U' R2' D R' D' R2 U D R' U D2", "M F' R U2' r' U r U2' R2' F r", "r' B' R F' R U2' r' U r U2' R2' FB r", "r' F2 r U' r U2' R' F R U2' r2' F' r", "L' r' F U' R' F' R U' R U R2' F R U L2'"],
    "RUB": ["R' B2' R2 U R' U R U' R2' B2' R U2' R U R' U'", "U R' U R U' x' U L' U L U2' R U' R' U x", "U' l R U2' R' U2 R' F R F' r U' r' F l'", "F U' R U R' U' R U R' F' R U R' U' R' F R2 U2' R' U F'", "U' R2 U D' R' F' R U2' r' U r' F' r2 U D R2' U", "D' R U' D R D' R2' D R U R' F D2 R' D2 R2 F'", "U' L U' L' U L2 F' L' F L' U B' U2 B U", "r' U2' r U R' B2' R U' R' B2' R2 U' R2' U2' R", "F2' l' R' F R' F' R2 U' R' F' U' F R U l F2'", "F2 R2 U D R' D' R U' R2' D R' D' F2", "F' R U2' R' U2 F' r U' r' F l' U' R U2 x'", "F R' U R' D R2 U' R U D' R' D R2 U' R D' F'", "S' U R' U R U' x' U L' U L U2 R U' R' U E", "F2' l' R' U' R2 U R2' D' R2 U R2' U' R2 U D x'", "R U2' R2' F R' F' R2 U' R' F' U' F R U R U2' R'", "L U' l R U2' R' U2 R' F R F' r U' r' F l' L'", "R U' D R D' R2' D R U R' F D2 R' D2 R2 F' D'", "R' U2' R2 U R2' U' R2 D R2' U' R2 U R2' U' D' R", "R U R' U R2 F2' R' U' R' U R U2' R F2' R2' U'", "R U' D' R' D R' U R D' R2' U' R2 U D R' U' R U R'", "R U R' U R U' R2' B2' R U2' R U R' U' R' B2' R", "f U' R U R' U' R U R' F' R U R' U' R' F R2 U2' R' U f'"],
    "RDB": ["U R U2 R U' R2' D R' U R U' D' R2 U' R' U'", "R U D R' F' R U R' U' R' F R2 U' R' U' R D' R'", "F U R F R' F' R2 U' R' U R U' R2' F' U'", "U' D2 R' F R U R' F U' F U F2 R D2", "D2 F' U' R' F' R2 U' R' U R' F R U D2", "D' r U' r' U r' F' r2 U2' R' F' R U' r' D", "U' E' R2' U' R U R2' U' D' R U R' U2'", "M R2 U' R' U R' F R U F' U' R' F' M'", "r R U' R' U r' F R U F' U' R' F'", "R M U2' F U' R' F' R U' R U R2' F R U' R' M'", "R' F R D R' F2 R D' R' F R2 D R2 F R2 D' R'", "U R' U' R U2 R' U' R S R f' U' F U2'", "R F' R' D' F' D R F R' D R' D' R", "R D' R' F R U R' F U' F U F2 R U' D R'", "D' F' r' F r F U' R U R2' F R F' D", "u R' U' R U2 R' U' R S R f' U' F U' u'", "U r' U r U R' U F' U F U2' R U2", "U' D' R D R2' U' D' R D R' U R2 U", "x D' r2' R F' R U2' r' U r U2' R2' F r2 D x'", "U2 R' U D' R U R' D R2 U' R U R2' U2' R U2", "U' R D' R' D2 R' U' R D' R' U D' R' D R U", "S' R F' R' D' F' D R F R' D R' D' R S"],
    "RDF": ["U' F' R U R' U' R' F R2 U' R' U' R U R' U", "U2' R' F R2 U' R' U' R U R' F' R U R' U", "R' F R U R U' R' F' R U2' R' U2 R U R'", "R' D' R U' R' F R U R' F U' F U F2 D R", "R u' R' U2 R' D' R U' R' U' D R' U R2 E' R'", "S' R U' R' U2 R' D' R U' R' U' D R' U R S", "U' E' R U' R2' D R' D' R2 U D R' E2 y", "R2 U R' F' R U R' U' R' F R2 U' R' U' R'", "l' F' U2 R' F R U' R' F' R U' F U' l", "U' F' R' F R F' r U2' R' U R U2' r' F U", "R' D' F R U R' F U' F U F2 D R U'", "R U' R' U D R' U' f' U' f U R D'", "D' R' F' R2 U' R' U R' u' R' u R F D", "r U' R' U r' F2 R F' R' F2 R", "F' U2 R' F R U' R' F' R U' F U'", "D' r' F D F' D R2 U' B U R2' D2 r D", "U' R U' R2' F R F' R U2' r' U r U' R' U", "U' R U' R2' D R' D' R2 U D R' U D'", "l' U' F' R U R' U' R' F R2 U' R' U' R U R' U l", "R U' R' U2 R' D' R U' R' U' D R' U R", "U' R U' R D R' U R' U F2 R D R' F2 R D' R'", "D' r' F2 r U' r U2' R' F R U2' r2' F' r D"],
    "BUR": ["U R' U' R2 U R' F' R U R' U' R' F R2 U' R' U' R' U R U'", "S U' R U R2' F R f' U R U R' U'", "R' F R' F' R2 U' R' U R f R' f'", "M' F' U' F R U R' F R' F' R2 U' r'", "U' R U R2' F R F' R' u' R u R", "U D r U' r' U' F R' F' R2 U' R' U D'", "LM' F' U' F R U R' F R' F' R2 U' r' L'", "M' U' R U r' R' F R F' U r U r' U'", "U r U' r' U' F R' F' R2 U' R' U", "r' R' F' R2 U' R' U R' F R U F' U' r", "S' R' F R' F' R2 U' R' U R f R' F'", "U R' U' F' U2' R' F R U' R' F' R U' F R U'", "U' R U R2' F R f' U R U R' U' S", "U' R U R2' E F R F' R' U' R u R", "U r' D' r U r' D r U2 r U' r' U r U r'", "u' R U R2' F R F' R' u' R u R E'", "U' R U R2' F R F' R U2' r' U r U R' U", "R' F R' F' R2 S U' R' U R F R' f'", "B U r' U2 l U' R' F2 r2 U' r' U' x", "R' U' D R2 U' R U R2' U' D' R U R' U R", "U' M' U2 r U' r' U' F R' F' R2 U' r' U", "U' D' M' U2 r U' r' U' F R' F' R2 U' r' U D"],
    "BUL": ["R D R' U R D' R2' U' R U R' U R U R' U' R U'", "r' U' F R' F' R2 U' R' U2 r U'", "U F R U R2' F R F' R U' R' F'", "b' R' U' R U b R' U' R U' R' U2 R U'", "F' U' R' F' R U F U' R U' R' U2", "S U F R U R2' F R F' R U' R' f'", "LM' U' R' F R F' U R U r' U2 R U R' U L'", "U2 R U D' R2 D R2 U' R' D' R D R' U R U", "U' L' U2 L F' L' U2 l2 F' l' U M' U", "F R U' R' F' R U' F U' F' U2' R'", "r U D' R U R' D R2' U' R U R2 U2' r'", "L U r' F U R U R' F' U2' F U F2 x", "r U D R' U' R D' R2 U R' U' R M", "r U2' R' F R U R' U' R' F' R2 U' R' U2 M", "U2 l U' R U R2' F R U F U' l' U", "L U' R U R' F' R U R' U' R' F R2 U' R' L'", "U' F R' F R F' R U2' r' U r U2' R' F' U", "U' F R U R' D R U' D' R2' D R D' R F' U", "U r' U2 l U' R' F2 r2 U' r' x", "U' D R' F2 r F' r' F2 R2 U' R' U2 D'", "U' R' F2 r F' r' F2 R2 U' R' U2", "U' D' R' F2 r F' r' F2 R2 U' R' U2 D"],
    "BDL": ["D F' r F2' R' D R F2' r2' D r D'", "U' R' D' R U R' U' D R D' R D R' U R' D' R D R     ", "x' U' F U' R' F' R U' R U R2' F R U2' x", "U' D R' F R U R' F U' F U F2 R D'", "D F' U' R' F' R2 U' R' U R' F R U D'", "U' D R' F R U F U2' R U R' U F' D'", "x' U' R r' F r' F2 R U' R' F2 r2 U' R' U x", "U' D' R' D R2 D' R' D2 R' U' R D' R' U2", "D F U2 R U R2' U' D' R U R' D R2 U F' D'", "D r' F2 r U' r' F2 r R U' r' F M' D'", "x' U D R U' R2' U R U2 R D R' U R D2 x", "D F U' F' U2' r2 U' F' U r2' U' D'", "D F U' F' U2' r' F R U' R' F' r U' D'", "r U r2' D r2 U' r2' U r2 U' r2' D r2 D' r'", "D R' U' R' F' R2 U' R' U2 R U2' R' F R U D'", "b' L U L' U L U2' L' U b L U L' U'", "U D r' D r U r' D' r U r' D r U r' D' r U D'", "U' D2 R D R2' U' D' R D R' U R2 U D", "B' U r' U2 l U' R' F2 r2 U' r' U x", "D F R U2' r' U r U2' R2' F R F2' D'", "L F U' R U2' r' U r U2' R' U F' U L' U'", "U' D' R D' R' D2 R' U' R D' R' U D' R' D R U D"],
    "BDR": ["U' D' F' R U R' U' R' F R2 U' R' U' R U R' U D", "U2 D' R' F R2 U' R' U' R U R' F' R U R' U D", "D' R U' R' U2 R' D' R U' R' D R U R U' R' U' D", "F U R U' R' F' U' R' U' R U R' F R' F' R2", "F' R F U' R' F' R U' R U R2' F R U R' F", "U' D' R U' R2' F R F' R U2' r' U r U' R' U D", "U' E' R U' D' R2' D R D' R2 U R' U2 y'", "D' R2 U R' F' R U R' U' R' F R2 U' R' U' R' D", "M' U' R' F' U' F R U r' F R' F' R2", "r' U2' F U' R' F' R U' R U R2' F R U' r", "M' U' R' F' U' F R U R' F R' F' R2M", "D' R U' R' U D R' U' f' U' f U R", "F R' U R' U' R2 U D R' U' R D' R' F'", "D' r U' R' U r' F2 R F' R' F2 R D", "U' F R' F' U' F R F' U2 R' U' R", "U D r' D r U' r' D R2 U' B U R2' D2 r D'", "D2 R' F' R2 U' R' U R' u' R' u R F D2", "U' D' R U' R2' D R' D' R2 U D R' U", "B2 U r' U2 l U' R' F2 r2 U' r' U2 x", "F R U' R' U R' U' D R' U D' R2 U F' U' R'", "D' R U' R' U2 R' D' R U' R' U' D R' U R D", "L' r' U2' F U' R' F' R U' R U R2' F R U' r2' x'"],
    "DFL": ["U' F2 R U R' U' R' F R2 U' R' U' R U R' F U", "U' r2' D' r2 U r2' U' r2 U r2' D' r2 D", "U2' F' U' R U' R' F R' F' R2 U' R' U2 R' F R U2'", "L D F' U' R' F' R2 U' R' U R' F R U D' L'", "U' R' F R U' R U R2' F R U F U' R' F2 R U", "r' U' r' F r2 D r' D' r U' F' U r U F' r'", "L U' D R' F R U R' F U' F U F2 R D' L'", "D' R' D' R D R2' f2 R D R' f2 R2 D", "U r U2' r' F U' R U' R' U2' F U' F'", "r' R' F R F' U r' F r U2' R U' R' U F r", "F U R U' R' F' R U' F U' F' U2 R' F U' F'", "F' R' F R2 U' R' D f' U R' U2' R f U D'", "F R' U' R' D R2 U' R U R2' U' D' R U2 R F'", "L r U r2' D r2 U' r2' U r2 U' r2' D r2 D' r2' x", "R U' r2' F r U' r U' F R U R' F' U2' R'", "u' R' F R U' R U R2' F R U F U' R' F2 R u", "U' F2 U F2 r U' R' F R F' r U r' U r'", "U' F' R U' R2' D R' D' R2 U D R' D' F U", "U' R U' R2' D R' U D' R U' R2' D R' U R U D'", "U2 R' F' R2 U R' U' R' F U F' R' F U' R U2", "U' F R' F2 r F' r' F2 R2 U' R' U F' U", "U' D' R' D' R D R' U R U' R U D' R2' D R2 D"],
    "DFR": ["U2' r U R' F2 r F' r' F2 R2 U' R' r' U2'", "U D R2' U' R2 U R2' D' R2 U R2' U' R2 U2", "R F U R' U' R F' U' R2 D' R U R' D R U R U2 R' ", "U D r2' F2 R U' R' F R U R' F U' F U r2 U' D'", "U' D' R' F R U' R U R2' F R U F U' R' F2 R U D", "U D R2' F2 R U' R' F R U R' F U' F U R2 U' D'", "r B2 R2' U' D' R D R' U R2 D' R D B2 r'", "U' D R' U' R D' R' D R' U R D' R2' U' R2 U2", "R' F2 R2 U' R U R2' F R U F U' R' F' R' F2 R", "M F' R2 U2' R' U2 R' F R F' r U' r' F R' M'", "U' F R2' D2 r D' r' D2 R2 F' R' F R F' U", "U' S' R U R' U2' f R F' U R' F R2 F'", "U' R U R' U2' f R f' U R' F R2 F'", "R' F2 R U r U r' U2 R U R2' F R F' R' F2 R", "U' r' D R' D' R2 U' R' F' R2 U R2' F r U2'", "R' D' R U L' U' R' D R U r2' U' r2 U' r F r'", "U2 R U' r' U R' U2' R U R' U R F R' F' r U'", "U' D R D' R U' R2' D R2 U R2' D' R U' R U R' U", "U' F U F' U' R' F' R2 U' R' U R' F R F' U", "F' R U R U' R' F U2' R F U' R' U R U F' R2'", "U2' R U R' F2 r F' r' F2 R2 U' R2' U2'", "U' D' F R' F2 r F' r' F2 R2 U' R' U F' U D"],
    "DBR": ["U R' U R U2' R' F R U R' U' R' F' R2 U' R' U R U'", "U R2' U' R2 U R2' D' R2 U R2' U' R2 U2 D", "R' U' R U R' F R' F' R2 F U R U' R' F' U'", "U r2' F2 R U' R' F R U R' F U' F U r2 U'", "R D' R' U' R' F' R U' R U R2' F R U F R D R'", "f' R F R' D R' D' R2 F' R' u' R' u f", "U2 l U R' F2 r F' r' U' r2 U r2' U x", "D R' D' R D R2' f2 R D R' f2 R2 D'", "U R2' F2 R U' R' F R U R' F U' F U R2 U'", "r U2' R' F' R U2' r' U r F r2' F' r2 F' r'", "R' U' F' U F R F' U R' U R U2 F R' U R", "U R' U' R U R2' F R F' R B U B' U'", "R U' F' U F R F' U R' U R U2 F R' U R'", "r D' r2' D' r2 U r2' U' r2 U r2' D' r2 U' D2 r'", "R' U' R U r' F R' F' R U' R' F R F' U r U'", "u R' U' R U R2' F R F' R B U B' u'", "U' D' R U R' U2' f R f' U R' F R2 F' D", "U' R D' R U' R2' D R2 U R2' D' R U' R U R' U D", "r2' D F2 r2 D r2' U' R U R' F2 r F' r", "U' D R' D' R D R' U R U' R U D' R2' D R2 D'", "U r2 U' R U R' F' R U R' U' R' F R2 U' r M' U'", "x U2' R' F' R U2' r' U r F r2' F' r2 F' x'"],
    "DBL": ["r2' U' D r2 U r2' D' r2 U' D r2' D' r2 U r2' D' r2", "U' D r2' D' r2 U r2' U' r2 U r2' D' r2", "R D' R2' F R' F' R2 U' R' U R f R' f' R D R'", "r L U' D' L U L' D L2' U' L U x'", "U' D R' F R U' R U R2' F R U F U' R' F2 R U D'", "F2' L' U2 R' F' R U2 r' U r' F' r2L F2'", "LM' U' R' U' R U R' F' R U R' U' R' F r M' x", "R' D' R D R2' f2 R D R' f2 R2", "L' R' F' R2 U' R' U R' u' R' u R F L", "z U2 R' F' R2 U' R' F' U' F R U R' F U2'", "l' U D R U' D' R U R' D R2' U' R U R U' D' l", "U D' R' U' R U R2' F R F' R B U B' U' D", "L r U D R' U' R D' R2 U R' U' M2 x", "L' F R U R' F U' F U F2 R U' M' x'", "L' r' F' R2 U' R' U R' u' R' u R F M' L", "B' l U' R U R2' F R U F U' R' F' U x", "l R U R U R2' F R U F U' R' F' R U2' R' l'", "r2 D' R' U R' U' R2 U D R' U' R D' R' D r2", "L2' l F' R U2' r' U r U2' R2' F r L", "r U' r2' U B' U' r2 U2' B' U' B r'", "U' R' D' R D R' U R U' R U D' R2' D R2", "R' F' R D R' F R D' R' F D F D' F' R"],
};

var commTest = {
    "comm": ["(R U R' U') (R' F R F')", "U: R' U' R2 U R2' U2' R S R2' S' R U R' U", "R U R', D", "R/S'", "[F: [D2, R U R']]", "R' U: D, R U' R'", "R' U: D, R U' R' + D: U, R' D' R"]
};

var f2e = {
    "UB": ["R U R' U R U2 R' U l' U' L U' L' U2 l U'", "M' U': M U M', U'", "S U' R: E, R' U2 R'", "U': U R' U R, S", "U' S R: E', R' U R'", "R E R', U' + U R': E, R U' R", "U' M' U': M, U R U", "M' U M, U'", "M' U r' S' R, U'", "U: U2 R U' R', S'", "M' U R S' r', U'", "L' U': S, U2 R' F R", "R': U R U, M", "U' M' U': M, U R' U", "S': U, M' U' M", "U R2': S, R F R", "M, U2 + U: S, R' F R", "U': S, U2 R' F R"],
    "UL": ["R' F R, S + S: R' E R, U'", "U2 R B' R', S", "R' F R, S + S: R E' R', U'", "S U' R: E, R' U R'", "M2' U': M, U R U", "M': M U M' U M, U2", "r' U': M', U R U", "L F' L', S' + S', U2", "M R U': M', U R' U", "S U' R': E', R U R", "R F R', S + S, R' B R'", "M2 U': M, U R' U", "U: U, M' U' M", "U, S' U' S", "M U' M', U'", "S, U' R U' R'"],
    "FR": ["U' l' U' M U R U M' U' B x'", "l2' U': M, U R U", "F' L': S', L F' L", "U F2 U' R' F' u' R2' u R F", "R U' r'M U M' U' R U r' U' M2' U", "R u' R E' R' U R' E R E' R'", "F' U' R: E, R' U R'", "l R U': M', U R' U", "U' M: M' U R S' r', U'", "U R': S, R F R", "M': U, M U' r S' R'", "R U R': S, R' F R'", "D' R U R': S, R' F R'", "U: L/E' + U: U, L E' L'"],
    "FL": ["S U' R: E, R' U' R'", "R' E: R U' R, E", "U' L': U, M' U M", "x r2' U': M', U R U", "R/E + R' F R, S'", "R E': R' U' R', E'", "E' L: M U' M', U'", "R2 U' R': E, R U R' U' R", "L' U: U, M' U' M", "R E R', U' + R'/E", "L': M U' M', U'", "R F R': R' F R', S'"],
    "DF": ["M': U, M U' R' S r", "l' U: S, U' R U' R'", "M': U, M U' R' S' r", "R F' R2': R U' R, E", "F' L': S', L F2' L", "D: R F R, S'", "r U': S, U R U' R2'", "R' F' R2: R' U' R', E", "r: M', U' R' U'", "L F' L': S', L F2' L"],
    "DB": ["r' U' r' S r U M' U R S R' U' R", "L: M U' M', U'", "U' R' U' F R S R' F' R S' r' U R U M'", "S': U, M U M'", "S U' r': E', R U R", "U' M: M' U r' S' R, U'", "R U R' U: M, U' R2 U'", "U' M: M' U r' S R, U'"],
    "DR": ["R F R, S'", "R' E' R, U' + R/E'", "R' U R: S, R' F R'", "R'/E' + R' F R, S'", "u': R/E' + E: R E' R', U'", "S', U' R2' U R2"],
    "DL": ["D' L: M U' M', U'", "u: L'/E' + u: U, L' E' L", "S U' R': E', R U' R", "l2 U': M, U R' U"],
    "RB": ["x' U' M' U R U M U' l'", "x' U M' U R U M U' R' U2' x"],
}

window.algs = {
    // "CMLL": CMLL,
    // "OH CMLL": oh_cmll,

    "UF edges (Elliott)": uf_edges,

    "UFR corners (Elliott)": ufr_corners,

    "2CO/2-Twists (James)": _2co,
    "UFR 3CO/3-Twists (James)": _3co,
    
    "2EO/2-Flips (Elliott)": _2eo,

    "Floating Parity": _3bld_parity,
    "UF/UFR Full Parity (Charlie)": full_parity,
    
    "LTCT (Andy Wong)": ltct_zeph,
    "LTCT (James)": ltct_james,

    "LTEF (LETTER PAIRS ONLY)": ltef,

    "T2C (Zeph/Elliott)": t2c,
    "F2E (James)": f2e,

    "UF-UR 2E2E (James)": uf_ur_2e2e,
    "UF-UR 2C (Zeph)": uf_ur_2c,

    // "comm test": commTest,
};